/* GS MUSUMBA R186.92 final compact/contrast loader.
   Heavy workspace CSS/JS load in parallel AFTER authenticated shell becomes visible.
   No login-page prefetch: heavy workspace assets load only after staff authentication. */
(function(){'use strict';
 if(window.GSM_loadAppExtensions)return;
 let promise=null;const started=performance.now();
 const APP_CSS='./r18661-app.css?v=R200.0',APP_JS='./r18661-extensions.js?v=R200.0',FINAL_CSS='./r18686-final.css?v=R200.0',FINAL_JS='./r18686-final.js?v=R200.0',CHECKLIST_JS='./r188-checklist-reporting.js?v=R200.0',CHECKLIST_CSS='./r188-checklist-reporting.css?v=R200.0',R200_CSS='./r200-professional.css?v=R200.0';
 const conn=()=>navigator.connection||navigator.mozConnection||navigator.webkitConnection||null;
 const slow=()=>{try{const c=conn();return !!(c&&(c.saveData||/slow-2g|2g/i.test(c.effectiveType||'')))}catch(_){return false}};
 function css(href){return new Promise((ok,bad)=>{if(document.querySelector('link[data-r18661-app]'))return ok();const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.r18661App='1';l.onload=ok;l.onerror=()=>{l.remove();bad(new Error('APP_CSS_LOAD_FAILED'))};document.head.appendChild(l)})}
 function js(src){return new Promise((ok,bad)=>{if(window.__GSM_R18661_EXTENSIONS_LOADED__)return ok();const s=document.createElement('script');s.src=src;s.async=true;s.dataset.r18661AppJs='1';s.onload=ok;s.onerror=()=>{s.remove();bad(new Error('APP_JS_LOAD_FAILED'))};document.head.appendChild(s)})}
 function finalCss(href){return new Promise((ok,bad)=>{if(document.querySelector('link[data-r18681-final]'))return ok();const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.r18681Final='1';l.onload=ok;l.onerror=()=>{l.remove();bad(new Error('FINAL_CSS_LOAD_FAILED'))};document.head.appendChild(l)})}
 function finalJs(src){return new Promise((ok,bad)=>{if(window.__GSM_R18681_FINAL__)return ok();const s=document.createElement('script');s.src=src;s.async=false;s.dataset.r18681FinalJs='1';s.onload=ok;s.onerror=()=>{s.remove();bad(new Error('FINAL_JS_LOAD_FAILED'))};document.head.appendChild(s)})}
 function checklistCss(src){return new Promise((ok,bad)=>{if(document.querySelector('link[data-r188-checklist]'))return ok();const l=document.createElement('link');l.rel='stylesheet';l.href=src;l.dataset.r188Checklist='1';l.onload=ok;l.onerror=()=>bad(new Error('CHECKLIST_CSS_LOAD_FAILED'));document.head.appendChild(l)})}
 function cssR200(src){return new Promise((ok,bad)=>{if(document.querySelector('link[data-r200-professional]'))return ok();const l=document.createElement('link');l.rel='stylesheet';l.href=src;l.dataset.r200Professional='1';l.onload=ok;l.onerror=()=>bad(new Error('R200_CSS_LOAD_FAILED'));document.head.appendChild(l)})}
 function checklistJs(src){return new Promise((ok,bad)=>{if(window.__GSM_R188_CHECKLIST__)return ok();const s=document.createElement('script');s.src=src;s.async=false;s.dataset.r188Checklist='1';s.onload=ok;s.onerror=()=>{s.remove();bad(new Error('CHECKLIST_JS_LOAD_FAILED'))};document.head.appendChild(s)})}
 function retry(fn,url){return fn(url).catch(()=>new Promise((ok,bad)=>setTimeout(()=>fn(url+(url.includes('?')?'&':'?')+'retry='+Date.now()).then(ok,bad),650)))}
 function dedupeSystemMenu(){const menus=window.GSM_MENUS||{};Object.values(menus).forEach(groups=>{if(!Array.isArray(groups))return;let seen=false;groups.forEach(g=>{if(!Array.isArray(g.items))return;g.items=g.items.filter(item=>{if(!/^system management$/i.test(String(item.label||'').trim()))return true;if(seen)return false;seen=true;return true})})})}
 window.GSM_loadAppExtensions=function(){if(promise)return promise;const t=performance.now();promise=Promise.all([retry(css,APP_CSS),retry(js,APP_JS)]).then(()=>{window.__GSM_R18661_EXTENSIONS_LOADED__=true;return Promise.all([retry(finalCss,FINAL_CSS),retry(finalJs,FINAL_JS),retry(checklistCss,CHECKLIST_CSS),retry(cssR200,R200_CSS)]).then(()=>retry(checklistJs,CHECKLIST_JS))}).then(()=>{dedupeSystemMenu();window.GSM_R18673_LOAD_METRICS={loaderReadyMs:Math.round(t-started),appLoadMs:Math.round(performance.now()-t),slowNetwork:slow(),parallelBase:true,finalAuthority:true,checklistReporting:true};return true}).catch(e=>{promise=null;throw e});return promise};
})();
