/* GS MUSUMBA R194 loader — preserves R193 and adds class-upload/QA patch. */
(function(){'use strict';
 if(window.GSM_loadAppExtensions)return;
 let promise=null;const started=performance.now();
 const APP_CSS='./r18661-app.css?v=R194',APP_JS='./r18661-extensions.js?v=R195.6',QA_JS='./r194-class-upload-live-qa.js?v=R194',ROLE_JS='./r194-role-menu.js?v=R194',ENCODING_JS='./r195-encoding-repair.js?v=R195.7',STUDENT_UPLOAD_JS='./r196-student-upload-fix.js?v=R196.1',MARKS_RESULTS_JS='./r197-marks-live-results.js?v=R197.1',CHECKLIST_CSS='./r188-checklist-reporting.css?v=R188.1',CHECKLIST_JS='./r188-checklist-reporting.js?v=R188.1';
 const conn=()=>navigator.connection||navigator.mozConnection||navigator.webkitConnection||null;
 const slow=()=>{try{const c=conn();return !!(c&&(c.saveData||/slow-2g|2g/i.test(c.effectiveType||'')))}catch(_){return false}};
 function css(href){return new Promise((ok,bad)=>{if(document.querySelector('link[data-r18661-app]'))return ok();const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.r18661App='1';l.onload=ok;l.onerror=()=>{l.remove();bad(new Error('APP_CSS_LOAD_FAILED'))};document.head.appendChild(l)})}
 function checklistCss(href){return new Promise((ok,bad)=>{if(document.querySelector('link[data-r188-checklist]'))return ok();const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.dataset.r188Checklist='1';l.onload=ok;l.onerror=()=>{l.remove();bad(new Error('CHECKLIST_CSS_LOAD_FAILED'))};document.head.appendChild(l)})}
 function js(src){return new Promise((ok,bad)=>{if(document.querySelector('script[data-r18661-app-js="'+src+'"]'))return ok();const s=document.createElement('script');s.src=src;s.async=true;s.dataset.r18661AppJs=src;s.onload=ok;s.onerror=()=>{s.remove();bad(new Error('APP_JS_LOAD_FAILED: '+src))};document.head.appendChild(s)})}
 function retry(fn,url){return fn(url).catch(()=>new Promise((ok,bad)=>setTimeout(()=>fn(url+(url.includes('?')?'&':'?')+'retry='+Date.now()).then(ok,bad),650)))}
 function prefetch(){try{if(slow())return;[[APP_CSS,'style'],[APP_JS,'script'],[QA_JS,'script'],[ROLE_JS,'script'],[ENCODING_JS,'script'],[STUDENT_UPLOAD_JS,'script'],[MARKS_RESULTS_JS,'script']].forEach(([href,as])=>{const key='gsm-prefetch-'+as+'-'+href;if(document.querySelector('link[data-gsm-prefetch="'+key+'"]'))return;const l=document.createElement('link');l.rel='prefetch';l.as=as;l.href=href;l.dataset.gsmPrefetch=key;document.head.appendChild(l)})}catch(_){}}
 function prefetch(){try{if(slow())return;[[APP_CSS,'style'],[APP_JS,'script'],[QA_JS,'script'],[ROLE_JS,'script'],[ENCODING_JS,'script'],[STUDENT_UPLOAD_JS,'script'],[MARKS_RESULTS_JS,'script'],[CHECKLIST_CSS,'style'],[CHECKLIST_JS,'script']].forEach(([href,as])=>{const key='gsm-prefetch-'+as+'-'+href;if(document.querySelector('link[data-gsm-prefetch="'+key+'"]'))return;const l=document.createElement('link');l.rel='prefetch';l.as=as;l.href=href;l.dataset.gsmPrefetch=key;document.head.appendChild(l)})}catch(_){}}
 window.GSM_loadAppExtensions=function(){if(promise)return promise;const t=performance.now();promise=Promise.all([retry(css,APP_CSS),retry(js,APP_JS),retry(js,ENCODING_JS)]).then(()=>retry(js,QA_JS)).then(()=>retry(js,ROLE_JS)).then(()=>retry(js,STUDENT_UPLOAD_JS)).then(()=>retry(js,MARKS_RESULTS_JS)).then(()=>Promise.all([retry(checklistCss,CHECKLIST_CSS),retry(js,CHECKLIST_JS)])).then(()=>{window.__GSM_R18661_EXTENSIONS_LOADED__=true;window.GSM_R18673_LOAD_METRICS={loaderReadyMs:Math.round(t-started),appLoadMs:Math.round(performance.now()-t),slowNetwork:slow(),parallel:true,qaLoaded:true,rolePatchLoaded:true,encodingRepairLoaded:true,studentUploadLoaded:true,marksResultsLoaded:true,checklistReporting:true};return true}).catch(e=>{promise=null;throw e});return promise};
 if('requestIdleCallback'in window)requestIdleCallback(prefetch,{timeout:2500});else setTimeout(prefetch,1800);
})();
