/* GS MUSUMBA R186.85 — LEAN TEACHER PORTAL
   One teacher UI, scoped by authenticated backend data. No embedded timetable authority.
   Authoritative marks formula results come from r174_teacher_marks_entry_data; the browser never recalculates CAMIS/final/grade/rank. */
(function(){
'use strict';
if(window.__GSM_R18685_TEACHER__)return;
window.__GSM_R18685_TEACHER__=true;

const V=window.GSM_VIEWS||{};
const M=window.GSM_MENUS||{};
const L=window.GSM_LIVE||{};
const U=window.GSM_UTIL||{};
const esc=U.esc||function(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const role=()=>String((window.BOOT&&BOOT.profile&&(BOOT.profile.role_code||BOOT.profile.role))||(LAST_CTX&&LAST_CTX.state&&LAST_CTX.state.role)||'').toUpperCase();
const RAW_RPC=(name,args={})=>L&&typeof L.rpc==='function'?L.rpc(name,args):Promise.reject(new Error('LIVE CONNECTION UNAVAILABLE'));
const WRITE_RPC=new Set(['r174_teacher_open_assessment','r174_teacher_save_marks','save_class_attendance','save_subject_attendance','r18685_teacher_save_student_profile','save_teacher_lesson_plan']);
const INFLIGHT=new Map();
const CALL_STATS={started:0,completed:0,failed:0,deduped:0,byRpc:{}};
window.GSM_R18685_TEACHER_DIAGNOSTICS=CALL_STATS;
function rpcKey(name,args){try{return name+'|'+JSON.stringify(args||{},Object.keys(args||{}).sort())}catch(_){return name+'|'+Date.now()}}
function rpc(name,args={}){
 const write=WRITE_RPC.has(name),key=write?null:rpcKey(name,args);
 if(key&&INFLIGHT.has(key)){CALL_STATS.deduped++;return INFLIGHT.get(key)}
 const started=performance.now();CALL_STATS.started++;CALL_STATS.byRpc[name]=CALL_STATS.byRpc[name]||{started:0,completed:0,failed:0,totalMs:0};CALL_STATS.byRpc[name].started++;
 const task=RAW_RPC(name,args).then(data=>{CALL_STATS.completed++;const x=CALL_STATS.byRpc[name];x.completed++;x.totalMs+=Math.round(performance.now()-started);return data}).catch(err=>{CALL_STATS.failed++;CALL_STATS.byRpc[name].failed++;throw err}).finally(()=>{if(key)INFLIGHT.delete(key)});
 if(key)INFLIGHT.set(key,task);return task;
}
const ctxIds=()=>({
  ayId:window.BOOT&&BOOT.context&&BOOT.context.academic_year_id||null,
  termId:window.BOOT&&BOOT.context&&BOOT.context.term_id||null,
  ay:window.BOOT&&BOOT.context&&BOOT.context.academic_year||'',
  term:window.BOOT&&BOOT.context&&BOOT.context.term||''
});
const iso=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())};
const fmtTime=v=>String(v||'').slice(0,5);
const num=v=>Number(v||0);
const pct=v=>v==null||v===''?'—':Number(v).toFixed(Number(v)%1?1:0)+'%';
const val=(v,d='—')=>v==null||v===''?d:String(v);
const norm=s=>String(s||'').trim().toUpperCase();
let LAST_CTX=null, FAST=null, FAST_PROMISE=null, ALL_TT=null, ALL_TT_AT=0, IDENT=null, IDENT_KEY='', IDENT_AT=0;
const ROSTER_CACHE=new Map();

/* R186.85 TEACHER DASHBOARD AUTHORITY: the historical R186.81 dashboard interceptor runs before GSM_VIEWS.dashboard.
   Let it keep serving other roles, but TEACHER must fall through to this lean portal dashboard. */
const LEGACY_DASH_RENDER=window.GSM_R18678_DASHBOARD_RENDER;
if(typeof LEGACY_DASH_RENDER==='function'&&!window.__GSM_R18685_TEACHER_DASH_GATE__){
 window.__GSM_R18685_TEACHER_DASH_GATE__=true;
 window.GSM_R18678_DASHBOARD_RENDER=function(mount,ctx){
  const r=String((ctx&&ctx.state&&ctx.state.role)||role()).toUpperCase();
  if(r==='TEACHER')return false;
  return LEGACY_DASH_RENDER(mount,ctx);
 };
}

M.TEACHER=[
 {title:'Teacher Workspace',items:[
  {id:'tc83_dash',label:'Dashboard',view:'dashboard'},
  {id:'tc83_timetable',label:'My Timetable',view:'teacherTimetable83'},
  {id:'tc83_classes',label:'My Classes',view:'teacherClasses83'},
  {id:'tc83_identification',label:'Students Identification',view:'teacherIdentification83'},
  {id:'tc83_classatt',label:'Class Attendance',view:'teacherClassAttendance83'},
  {id:'tc83_subjectatt',label:'Subject Attendance',view:'teacherSubjectAttendance83'},
  {id:'tc83_marks',label:'Marks & Assessments',view:'teacherMarks83'},
  {id:'tc83_performance',label:'Student Performance',view:'teacherPerformance83'},
  {id:'tc83_reports',label:'Reports',view:'teacherReports83'}
 ]},
 {title:'Planning & Co-curricular',items:[
  {id:'tc85_club',label:'My Club',view:'teacherClub85'},
  {id:'tc85_lessons',label:'Lesson Plans',view:'teacherLessonPlans85'}
 ]},
 {title:'Account',items:[{id:'tc83_account',label:'Account',view:'teacherAccount83'}]}
];

function nav(ctx,id){LAST_CTX=ctx||LAST_CTX;const allowed=(M.TEACHER||[]).some(sec=>(sec.items||[]).some(it=>it.id===id));if(!allowed){notify('Service route is unavailable: '+id,'error');return false}if(LAST_CTX&&typeof LAST_CTX.navigateToId==='function'){LAST_CTX.navigateToId(id);return true}const b=document.querySelector('.side-link[data-id="'+CSS.escape(id)+'"]');if(b){b.click();return true}notify('Service could not open. Please retry.','error');return false}
function page(mount,ctx,service=true){LAST_CTX=ctx||LAST_CTX;mount.className='t83-page';document.body.classList.remove('t83-service-open','gsm77-service-focus','gsm77-nested-open');document.body.setAttribute('data-t83-view',service?'service':'dashboard');const crumb=document.getElementById('crumb');if(crumb)crumb.textContent='TEACHER PORTAL'}
function head(title,sub='',actions=''){
 return '<div class="t83-head"><div class="t83-head-copy"><small>GS MUSUMBA · TEACHER PORTAL · R186.85</small><h2>'+esc(title)+'</h2><p>'+esc(sub)+'</p></div><div class="t83-actions">'+actions+'</div></div><div class="t83-flash" data-t83-flash></div>';
}
function serviceHead(title,sub='',extra=''){
 return head(title,sub,'<button class="t83-btn light small" data-t83-back>← BACK</button>'+extra+'<button class="t83-btn red small" data-t83-close>✕ CLOSE</button>');
}
function wireBack(mount,ctx){$$('[data-t83-back],[data-t83-close]',mount).forEach(b=>b.onclick=()=>nav(ctx,'tc83_dash'))}
function flash(mount,msg,type='info'){
 const el=$('[data-t83-flash]',mount);if(!el)return;
 el.className='t83-flash show '+type;el.textContent=msg;
 if(type==='success')setTimeout(()=>{if(el.textContent===msg)el.className='t83-flash'},2400);
}
function notify(msg,type='info'){
 try{if(U&&typeof U.toast==='function'){U.toast(msg);return}}catch(_){}
 let n=document.getElementById('t85GlobalNotice');if(!n){n=document.createElement('div');n.id='t85GlobalNotice';n.className='t85-global-notice';document.body.appendChild(n)}n.className='t85-global-notice show '+type;n.textContent=msg;clearTimeout(n.__timer);n.__timer=setTimeout(()=>n.className='t85-global-notice',3200)
}
function errorText(e){const s=String(e&&e.message||e||'Operation failed').replace(/^Error:\s*/,'');return s.replace(/_/g,' ')}
function busy(btn,label){if(!btn)return()=>{};const old=btn.textContent;btn.disabled=true;btn.setAttribute('aria-busy','true');btn.textContent=label||'WORKING…';return()=>{btn.disabled=false;btn.removeAttribute('aria-busy');btn.textContent=old}}
function empty(msg){return '<div class="t83-empty">'+esc(msg)+'</div>'}
function kpi(n,label,kind='light',small='',go=''){const tag=go?'button':'div',attr=go?' type="button" data-go="'+esc(go)+'"':'';return '<'+tag+' class="t83-kpi '+kind+(go?' t83-kpi-action':'')+'"'+attr+'><strong>'+esc(n)+'</strong><span>'+esc(label)+'</span>'+(small?'<small>'+esc(small)+'</small>':'')+'</'+tag+'>'}
function kpiFilter(n,label,kind,status){return '<button type="button" class="t83-kpi '+kind+' t83-kpi-action" data-ident-card="'+esc(status)+'"><strong>'+esc(n)+'</strong><span>'+esc(label)+'</span></button>'}
function panel(title,sub,body,action=''){return '<section class="t83-panel"><div class="t83-panel-h"><div><h3>'+esc(title)+'</h3>'+(sub?'<small>'+esc(sub)+'</small>':'')+'</div>'+action+'</div><div class="t83-panel-b">'+body+'</div></section>'}
function goButtons(mount,ctx){$$('[data-go]',mount).forEach(b=>b.onclick=()=>nav(ctx,b.dataset.go))}
function statusClass(s){s=norm(s);return s==='VERIFIED'?'verified':s==='READY'?'ready':s==='COMPLETE'?'complete':s==='NOT_STARTED'?'notstarted':'incomplete'}
function statusText(s){s=norm(s);return s==='NOT_STARTED'?'NOT STARTED':s||'INCOMPLETE'}
function subjectClass(name,code){const s=norm(name+' '+code);if(/MATH|IMIBARE/.test(s))return't83-subj-math';if(/ENGLISH|ICYONGEREZA/.test(s))return't83-subj-eng';if(/KINY|IKINYARWANDA/.test(s))return't83-subj-kin';if(/FRENCH/.test(s))return't83-subj-fre';if(/SWAHILI|KISWAHILI/.test(s))return't83-subj-swa';if(/SCIENCE|BIOLOGY|CHEMISTRY|PHYSICS|SET/.test(s))return't83-subj-sci';if(/HISTORY/.test(s))return't83-subj-hist';if(/GEOGRAPH/.test(s))return't83-subj-geo';if(/RELIG|SRE|SOCIAL AND RELIGIOUS/.test(s))return't83-subj-sre';if(/ENTREPRENEUR/.test(s))return't83-subj-ent';if(/ICT|COMPUT/.test(s))return't83-subj-ict';if(/PHYSICAL|SPORT|PES/.test(s))return't83-subj-pes';if(/ART|MUSIC|UBUGENI/.test(s))return't83-subj-art';return't83-subj-other'}
function uniqueStudentCount(classes){return (classes||[]).reduce((a,c)=>a+num(c.student_count),0)}
function fastKey(){const c=ctxIds(),sid=window.BOOT&&BOOT.profile&&BOOT.profile.staff_id||'';return 'gsm_t83_fast_'+sid+'_'+c.ayId+'_'+c.termId}
function readFastCache(){try{const x=JSON.parse(sessionStorage.getItem(fastKey())||'null');if(x&&x.data&&Date.now()-x.time<300000)return x.data}catch(_){}return null}
function getFast(force=false){
 if(!force&&FAST)return Promise.resolve(FAST);
 if(!force&&!FAST){const cached=readFastCache();if(cached)FAST=cached}
 if(!force&&FAST)return Promise.resolve(FAST);
 if(!force&&FAST_PROMISE)return FAST_PROMISE;
 const c=ctxIds();FAST_PROMISE=rpc('r174_teacher_fast_bootstrap',{p_academic_year_id:c.ayId,p_term_id:c.termId}).then(d=>{FAST=d;try{sessionStorage.setItem(fastKey(),JSON.stringify({time:Date.now(),data:d}))}catch(_){}return d}).finally(()=>FAST_PROMISE=null);return FAST_PROMISE;
}
function getAllTimetable(force=false){if(ALL_TT&&!force&&Date.now()-ALL_TT_AT<300000)return Promise.resolve(ALL_TT);return rpc('r136_teacher_timetable',{}).then(d=>{ALL_TT=d;ALL_TT_AT=Date.now();return d})}
function dayOrder(d){return({MONDAY:1,TUESDAY:2,WEDNESDAY:3,THURSDAY:4,FRIDAY:5})[norm(d)]||9}

/* ========================= DASHBOARD ========================= */
const OLD_DASH=V.dashboard;
V.dashboard=function(mount,ctx){
 if(role()!=='TEACHER')return OLD_DASH&&OLD_DASH(mount,ctx);
 page(mount,ctx,false);
 const c=ctxIds(),cached=FAST||readFastCache();
 mount.innerHTML=head('Teacher Dashboard',(window.BOOT&&BOOT.profile&&BOOT.profile.full_name||'Teacher')+' · '+c.ay+' · '+c.term,
   '<button class="t83-btn blue small" data-t83-refresh>↻ REFRESH</button>')+
   '<div data-t83-dashboard-body>'+(cached?dashboardHtml(cached,null):dashboardPendingHtml())+'</div>';
 wireDashboard(mount,ctx);
 if(cached){FAST=cached;loadDashboardMetrics(mount,cached)}
 else getFast().then(d=>{const body=$('[data-t83-dashboard-body]',mount);if(!body)return;body.innerHTML=dashboardHtml(d,null);wireDashboard(mount,ctx);loadDashboardMetrics(mount,d)}).catch(e=>{flash(mount,'Dashboard could not open: '+errorText(e),'error');const body=$('[data-t83-dashboard-body]',mount);if(body)body.innerHTML=dashboardRetryHtml();wireDashboard(mount,ctx)});
 const rb=$('[data-t83-refresh]',mount);if(rb)rb.onclick=()=>{const done=busy(rb,'REFRESHING…');FAST=null;ALL_TT=null;ALL_TT_AT=0;getFast(true).then(d=>{const body=$('[data-t83-dashboard-body]',mount);if(body)body.innerHTML=dashboardHtml(d,null);wireDashboard(mount,ctx);loadDashboardMetrics(mount,d);flash(mount,'Dashboard refreshed.','success')}).catch(e=>flash(mount,'Refresh failed: '+errorText(e),'error')).finally(done)};
};
function dashboardPendingHtml(){return '<div class="t83-kpis">'+kpi('—','MY CLASSES','blue','','tc83_classes')+kpi('—','MY STUDENTS','green','','tc83_identification')+kpi('—','ATTEND. TO DO','gold','','tc83_classatt')+kpi('—','ACTION NEEDED','red','','tc83_reports')+'</div>'+panel("TODAY'S TIMETABLE",'The page is ready; current live scope is being confirmed.','<div class="t85-inline-state">Connecting to current teacher data…</div>','<button class="t83-btn light small" data-go="tc83_timetable">FULL WEEK</button>')+panel('QUICK WORK','Open a service immediately','<div class="t83-quick"><button data-go="tc83_identification">STUDENT IDENTIFICATION</button><button data-go="tc83_classatt">CLASS ATTENDANCE</button><button data-go="tc83_marks">MARKS</button><button data-go="tc83_performance">PERFORMANCE</button></div>')}
function dashboardRetryHtml(){return '<div class="t83-kpis">'+kpi('—','MY CLASSES','blue','','tc83_classes')+kpi('—','MY STUDENTS','green','','tc83_identification')+kpi('—','ATTEND. TO DO','gold','','tc83_classatt')+kpi('—','ACTION NEEDED','red','','tc83_reports')+'</div>'+panel('LIVE DATA UNAVAILABLE','The navigation remains active. Use Refresh after checking the network.','<div class="t85-inline-error">Live counters could not be retrieved. No data was changed.</div>')}
function dashboardHtml(d,metrics){
 const classes=d&&d.classes||[],tt=d&&d.today_timetable||[],students=uniqueStudentCount(classes),att=metrics?num(metrics.class_attendance_pending_today)+num(metrics.subject_attendance_pending_today):'—',actions=metrics?num(metrics.action_required_total):'—';
 const next=tt.slice().sort((a,b)=>String(a.start_time).localeCompare(String(b.start_time))).slice(0,6);
 const today=next.length?'<div class="t83-list">'+next.map(x=>'<div class="t83-list-row"><div><b>'+esc(fmtTime(x.start_time)+'–'+fmtTime(x.end_time)+' · '+val(x.subject_name,x.display_label||'LESSON'))+'</b><span>'+esc(x.class_code||'')+(x.room?' · '+esc(x.room):'')+'</span></div><strong>'+esc(x.lesson_number!=null?'P'+x.lesson_number:'')+'</strong></div>').join('')+'</div>':empty('No published lesson is scheduled for today.');
 const actionBody='<div class="t83-list" data-t83-actions-list>'+(metrics?actionRows(metrics):'<div class="t85-inline-state">Checking today’s pending work…</div>')+'</div>';
 const target=!metrics?'tc83_reports':(num(metrics.profiles_incomplete)+num(metrics.profiles_not_started)>0?'tc83_identification':num(metrics.class_attendance_pending_today)>0?'tc83_classatt':num(metrics.subject_attendance_pending_today)>0?'tc83_subjectatt':num(metrics.marks_pending)+num(metrics.marks_returned)>0?'tc83_marks':'tc83_reports');
 return '<div class="t83-kpis" data-t83-dashboard-kpis>'+kpi(classes.length,'MY CLASSES','blue','','tc83_classes')+kpi(students,'MY STUDENTS','green','','tc83_identification')+kpi(att,'ATTEND. TO DO',att===0?'green':'gold','','tc83_classatt')+kpi(actions,'ACTION NEEDED',actions===0?'green':'red','',target)+'</div>'+
 '<div class="t83-grid2">'+panel("TODAY'S TIMETABLE",'Published live timetable',today,'<button class="t83-btn light small" data-go="tc83_timetable">FULL WEEK</button>')+panel('ACTION / ATTENTION','Only current items that need follow-up',actionBody)+'</div>'+
 panel('QUICK WORK','One click opens one service','<div class="t83-quick"><button data-go="tc83_identification">STUDENT IDENTIFICATION</button><button data-go="tc83_classatt">CLASS ATTENDANCE</button><button data-go="tc83_marks">MARKS</button><button data-go="tc83_performance">PERFORMANCE</button></div>');
}
function actionRows(m){
 const rows=[
  ['Student profiles',num(m.profiles_incomplete)+num(m.profiles_not_started),'tc83_identification'],
  ['Class attendance today',num(m.class_attendance_pending_today),'tc83_classatt'],
  ['Subject attendance today',num(m.subject_attendance_pending_today),'tc83_subjectatt'],
  ['Marks pending / returned',num(m.marks_pending)+num(m.marks_returned),'tc83_marks']
 ];
 return rows.map(x=>'<div class="t83-list-row"><button class="t83-btn light small" data-go="'+x[2]+'">'+esc(x[0])+'</button><strong>'+x[1]+'</strong></div>').join('');
}
function wireDashboard(mount,ctx){goButtons(mount,ctx)}
function loadDashboardMetrics(mount,d){
 const c=ctxIds();
 const run=()=>rpc('r18683_teacher_dashboard_metrics',{p_academic_year_id:c.ayId,p_term_id:c.termId}).then(m=>{const body=$('[data-t83-dashboard-body]',mount);if(!body)return;body.innerHTML=dashboardHtml(d,m);wireDashboard(mount,LAST_CTX)}).catch(e=>{const list=$('[data-t83-actions-list]',mount);if(list)list.innerHTML='<div class="t85-inline-error">Some counters are unavailable. <button class="t83-btn light small" data-metric-retry>RETRY</button></div>';const b=$('[data-metric-retry]',mount);if(b)b.onclick=run;flash(mount,'Some dashboard counters could not refresh. Core services remain available.','warn')});
 if('requestIdleCallback' in window)requestIdleCallback(run,{timeout:700});else setTimeout(run,60);
}

/* ========================= TIMETABLE ========================= */
V.teacherTimetable83=function(mount,ctx){
 page(mount,ctx,true);mount.innerHTML=serviceHead('My Timetable','Live Supabase · current published timetable','<button class="t83-btn blue small" data-t83-print>PRINT</button><button class="t83-btn green small" data-t83-refresh>REFRESH</button>')+'<div data-t83-tt><div class="t85-inline-state">Timetable area is ready; confirming the current published rows…</div></div>';wireBack(mount,ctx);
 const draw=(force=false)=>getAllTimetable(force).then(d=>{const rows=d&&d.rows||[];$('[data-t83-tt]',mount).innerHTML=timetableHtml(rows)}).catch(e=>{$('[data-t83-tt]',mount).innerHTML=empty('Timetable unavailable: '+errorText(e))});draw();
 $('[data-t83-print]',mount).onclick=()=>window.print();const rb=$('[data-t83-refresh]',mount);rb.onclick=()=>{const done=busy(rb,'REFRESHING…');draw(true).then(()=>flash(mount,'Timetable refreshed.','success')).finally(done)};
};
function timetableHtml(rows){
 const days=['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY'];const slots=[];const seen=new Set();
 rows.slice().sort((a,b)=>num(a.lesson_number)-num(b.lesson_number)||String(a.start_time).localeCompare(String(b.start_time))).forEach(r=>{const k=[r.lesson_number,r.start_time,r.end_time].join('|');if(!seen.has(k)){seen.add(k);slots.push({key:k,n:r.lesson_number,start:r.start_time,end:r.end_time})}});
 const map=new Map(rows.map(r=>[[r.lesson_number,r.start_time,r.end_time,norm(r.day_of_week)].join('|'),r]));
 let desk='<div class="t83-table-wrap t83-desktop-only t83-tt"><table class="t83-table"><thead><tr><th>PERIOD / HOUR</th>'+days.map(d=>'<th>'+d+'</th>').join('')+'</tr></thead><tbody>';
 slots.forEach(s=>{desk+='<tr><td class="center"><b>P'+esc(s.n==null?'':s.n)+'</b><br>'+esc(fmtTime(s.start)+'–'+fmtTime(s.end))+'</td>';days.forEach(d=>{const r=map.get([s.n,s.start,s.end,d].join('|'));desk+=r?'<td class="t83-tt-cell '+subjectClass(r.subject_name,r.subject_code)+'">'+esc(val(r.subject_name,r.display_label||'LESSON'))+'<small>'+esc(r.class_code||'')+(r.room?' · '+esc(r.room):'')+'</small></td>':'<td class="t83-tt-empty"></td>'});desk+='</tr>'});desk+='</tbody></table></div>';
 const mobile='<div class="t83-mobile-list">'+days.map(d=>panel(d,'',((rows.filter(r=>norm(r.day_of_week)===d).sort((a,b)=>String(a.start_time).localeCompare(String(b.start_time))).map(r=>'<div class="t83-mobile-card '+subjectClass(r.subject_name,r.subject_code)+'" style="color:#fff"><div class="top"><b style="color:#fff">'+esc(fmtTime(r.start_time)+'–'+fmtTime(r.end_time))+'</b><small style="color:#fff">'+esc(r.class_code||'')+'</small></div><div class="meta" style="color:#fff"><b style="color:#fff">'+esc(val(r.subject_name,r.display_label||'LESSON'))+'</b>'+(r.room?' · '+esc(r.room):'')+'</div></div>').join(''))||empty('No lesson')))).join('')+'</div>';
 return desk+mobile;
}

/* ========================= MY CLASSES ========================= */
V.teacherClasses83=function(mount,ctx){
 page(mount,ctx,true);mount.innerHTML=serviceHead('My Classes','Only classes in your authenticated teaching scope','<button class="t83-btn green small" data-t83-refresh>REFRESH</button>')+'<div data-t83-classes><div class="t85-inline-state">Class area is ready; confirming your current teaching scope…</div></div>';wireBack(mount,ctx);
 const draw=force=>getFast(!!force).then(d=>{const classes=d.classes||[],assign=d.assignments||[];$('[data-t83-classes]',mount).innerHTML='<div class="t83-class-grid">'+classes.map(c=>{const ss=assign.filter(a=>String(a.class_id)===String(c.class_id)).map(a=>a.subject_name),manage=!!c.is_class_teacher;return '<article class="t83-class-card"><h3>'+esc(c.class_code)+'</h3><p>'+esc(c.class_name||'')+' · '+num(c.student_count)+' students</p><p>'+esc(ss.slice(0,3).join(' · ')||(manage?'Class teacher scope':'Teaching scope'))+(ss.length>3?' +'+(ss.length-3):'')+'</p><div class="actions"><button class="t83-btn blue small" data-roster="'+esc(c.class_id)+'">STUDENTS</button>'+(manage?'<button class="t83-btn green small" data-ident="'+esc(c.class_id)+'">IDENTIFICATION</button><button class="t83-btn gold small" data-att="'+esc(c.class_id)+'">CLASS ATTENDANCE</button>':'')+'</div></article>'}).join('')+'</div>';wireClassCards(mount,ctx)}).catch(e=>{$('[data-t83-classes]',mount).innerHTML=empty(errorText(e))});draw(false);
 const rb=$('[data-t83-refresh]',mount);rb.onclick=()=>{FAST=null;const done=busy(rb,'REFRESHING…');draw(true).finally(done)};
};
function wireClassCards(mount,ctx){
 $$('[data-ident]',mount).forEach(b=>b.onclick=()=>{window.__T83_CLASS_FILTER=b.dataset.ident;nav(ctx,'tc83_identification')});
 $$('[data-att]',mount).forEach(b=>b.onclick=()=>{window.__T83_CLASS_ATT=b.dataset.att;nav(ctx,'tc83_classatt')});
 $$('[data-roster]',mount).forEach(b=>b.onclick=()=>{
   const id=b.dataset.roster,cached=ROSTER_CACHE.get(id);
   if(cached&&Date.now()-cached.at<120000){renderRoster(mount,cached.data,ctx);return}
   const done=busy(b,'OPENING…');rpc('r174_teacher_class_roster',{p_class_id:id}).then(d=>{ROSTER_CACHE.set(id,{at:Date.now(),data:d});renderRoster(mount,d,ctx)}).catch(e=>flash(mount,'Class list could not open: '+errorText(e),'error')).finally(done)
 });
}
function rosterTableHtml(rows,manage){return '<div class="t83-table-wrap t83-desktop-only"><table class="t83-table t83-roster-table"><colgroup><col style="width:52px"><col style="width:150px"><col><col style="width:88px"><col style="width:112px"></colgroup><thead><tr><th>NO</th><th>SDMS</th><th>STUDENT NAME</th><th>SEX</th><th>ACTION</th></tr></thead><tbody>'+rows.map((r,i)=>'<tr><td class="center">'+(i+1)+'</td><td>'+esc(r.sdms_code)+'</td><td class="name">'+esc(r.student_name)+'</td><td class="center">'+esc(r.sex)+'</td><td class="center">'+(manage?'<button class="t83-btn blue small" data-stu-ident="'+esc(r.student_id)+'">PROFILE</button>':'VIEW ONLY')+'</td></tr>').join('')+'</tbody></table></div>'}
function rosterMobileHtml(rows,manage){return '<div class="t83-mobile-list">'+rows.map(r=>'<div class="t83-mobile-card"><div class="top"><b>'+esc(r.student_name)+'</b><small>'+esc(r.sex)+'</small></div><div class="meta">SDMS '+esc(r.sdms_code)+'</div>'+(manage?'<button class="t83-btn blue small" data-stu-ident="'+esc(r.student_id)+'">PROFILE</button>':'<div class="meta">View-only teaching scope</div>')+'</div>').join('')+'</div>'}
function renderRoster(mount,d,ctx){
 const c=d.class||{},all=d.rows||[],manage=(FAST&&FAST.classes||[]).some(x=>String(x.class_id)===String(c.id)&&x.is_class_teacher);
 mount.innerHTML=serviceHead('My Class · '+val(c.class_code,''),num(d.student_count)+' students · '+(manage?'Class-teacher management scope':'Teaching scope · student list is view only'),'<button class="t83-btn blue small" data-t83-print>PRINT</button>')+
 '<div class="t83-toolbar t83-roster-tools"><div class="t83-field t83-search"><label>Search student / SDMS</label><input data-roster-search placeholder="Type student name or SDMS…"></div><div class="t83-field"><label>Showing</label><div class="t85-count" data-roster-count>'+all.length+' STUDENTS</div></div></div><div data-roster-results></div>';
 wireBack(mount,ctx);$('[data-t83-print]',mount).onclick=()=>window.print();
 const results=$('[data-roster-results]',mount),search=$('[data-roster-search]',mount),count=$('[data-roster-count]',mount);
 const draw=()=>{const q=norm(search.value),rows=q?all.filter(r=>norm((r.student_name||'')+' '+(r.sdms_code||'')).includes(q)):all.slice();count.textContent=rows.length+' / '+all.length+' STUDENTS';results.innerHTML=rows.length?rosterTableHtml(rows,manage)+rosterMobileHtml(rows,manage):empty('No students match this search.');$$('[data-stu-ident]',results).forEach(b=>b.onclick=()=>{window.__T83_OPEN_STUDENT=b.dataset.stuIdent;window.__T83_CLASS_FILTER=c.id;nav(ctx,'tc83_identification')})};
 search.addEventListener('input',draw);draw();
}

/* ========================= STUDENT IDENTIFICATION ========================= */
V.teacherIdentification83=function(mount,ctx){
 page(mount,ctx,true);mount.innerHTML=serviceHead('Students Identification','Search → filter → Edit Profile → Save & Next Incomplete','<button class="t83-btn green small" data-t83-refresh>REFRESH</button>')+'<div data-t83-ident><div class="t85-inline-state">Opening your student list…</div></div>';wireBack(mount,ctx);
 const c=ctxIds(),classId=window.__T83_CLASS_FILTER||null;delete window.__T83_CLASS_FILTER;const cacheKey=[c.ayId,c.termId,classId||'ALL'].join('|');
 const load=force=>{
   if(!force&&IDENT&&IDENT_KEY===cacheKey&&Date.now()-IDENT_AT<120000){renderIdentList(mount,ctx,IDENT,classId);const open=window.__T83_OPEN_STUDENT;delete window.__T83_OPEN_STUDENT;if(open)openStudentProfile(mount,ctx,open,IDENT);return Promise.resolve(IDENT)}
   return rpc('r18685_teacher_identification_directory',{p_academic_year_id:c.ayId,p_term_id:c.termId,p_class_id:classId,p_search:null,p_sort:'NAME_ASC',p_status:'ALL',p_limit:500,p_offset:0}).then(d=>{IDENT=d;IDENT_KEY=cacheKey;IDENT_AT=Date.now();renderIdentList(mount,ctx,d,classId);const open=window.__T83_OPEN_STUDENT;delete window.__T83_OPEN_STUDENT;if(open)openStudentProfile(mount,ctx,open,d);return d}).catch(e=>{const root=$('[data-t83-ident]',mount);if(root)root.innerHTML=empty('Student identification unavailable: '+errorText(e));flash(mount,'Student list could not open: '+errorText(e),'error');throw e})
 };
 load(false).catch(()=>{});
 const rb=$('[data-t83-refresh]',mount);rb.onclick=()=>{const done=busy(rb,'REFRESHING…');load(true).then(()=>flash(mount,'Student list refreshed.','success')).catch(()=>{}).finally(done)};
};
function renderIdentList(mount,ctx,d,lockedClass){
 d.__lockedClass=lockedClass||d.__lockedClass||null;lockedClass=d.__lockedClass;
 const s=d.summary||{},rows=d.rows||[],classes=[...new Map(rows.map(r=>[r.class_id,{id:r.class_id,code:r.class_code}])).values()];
 const missing=[...new Set(rows.flatMap(r=>Array.isArray(r.missing_fields)?r.missing_fields:[]))].sort();
 const root=$('[data-t83-ident]',mount);if(!root)return;
 root.innerHTML='<div class="t83-kpis">'+kpiFilter(num(s.total),'TOTAL','blue','ALL')+kpiFilter(num(s.complete),'COMPLETE','green','COMPLETE')+kpiFilter(num(s.incomplete),'INCOMPLETE','gold','INCOMPLETE')+kpiFilter(num(s.not_started),'NOT STARTED','red','NOT_STARTED')+'</div>'+
 '<div class="t83-status-tabs" data-ident-tabs>'+['ALL','COMPLETE','INCOMPLETE','NOT_STARTED','READY','VERIFIED'].map((x,i)=>'<button class="'+(i===0?'active':'')+'" data-status="'+x+'">'+statusText(x)+'</button>').join('')+'</div>'+
 '<div class="t83-toolbar"><div class="t83-field t83-search"><label>Search student / SDMS</label><input data-ident-search placeholder="Type name or SDMS…"></div><div class="t83-field"><label>Class</label><select data-ident-class><option value="">ALL MY CLASSES</option>'+classes.map(c=>'<option value="'+esc(c.id)+'" '+(lockedClass&&String(lockedClass)===String(c.id)?'selected':'')+'>'+esc(c.code)+'</option>').join('')+'</select></div><div class="t83-field"><label>Missing Data</label><select data-ident-missing><option value="">ALL MISSING</option>'+missing.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></div><div class="t83-field"><label>Sort</label><select data-ident-sort><option value="NAME_ASC">NAME A-Z</option><option value="NAME_DESC">NAME Z-A</option><option value="COMPLETION_ASC">MOST INCOMPLETE</option><option value="COMPLETION_DESC">MOST COMPLETE</option><option value="UPDATED_DESC">RECENTLY UPDATED</option></select></div></div><div data-ident-results></div>';
 const state={status:'ALL'};
 const redraw=()=>{let x=rows.slice(),q=norm($('[data-ident-search]',root).value),cl=$('[data-ident-class]',root).value,mi=$('[data-ident-missing]',root).value,sort=$('[data-ident-sort]',root).value;if(q)x=x.filter(r=>norm(r.full_name+' '+r.sdms_code).includes(q));if(cl)x=x.filter(r=>String(r.class_id)===String(cl));if(mi)x=x.filter(r=>(r.missing_fields||[]).includes(mi));if(state.status!=='ALL')x=x.filter(r=>state.status==='COMPLETE'?num(r.completion_percent)>=100:norm(r.status_label)===state.status);x.sort((a,b)=>sort==='NAME_DESC'?String(b.full_name).localeCompare(String(a.full_name)):sort==='COMPLETION_ASC'?num(a.completion_percent)-num(b.completion_percent):sort==='COMPLETION_DESC'?num(b.completion_percent)-num(a.completion_percent):sort==='UPDATED_DESC'?String(b.updated_at).localeCompare(String(a.updated_at)):String(a.full_name).localeCompare(String(b.full_name)));drawIdentRows(root,x,ctx,d)};
 $$('[data-status]',root).forEach(b=>b.onclick=()=>{$$('[data-status]',root).forEach(x=>x.classList.remove('active'));b.classList.add('active');state.status=b.dataset.status;redraw()});
 $$('[data-ident-card]',root).forEach(b=>b.onclick=()=>{const status=b.dataset.identCard,t=$('[data-status="'+CSS.escape(status)+'"]',root);if(t)t.click()});
 ['[data-ident-search]','[data-ident-class]','[data-ident-missing]','[data-ident-sort]'].forEach(sel=>{const e=$(sel,root);e.addEventListener(e.tagName==='INPUT'?'input':'change',redraw)});redraw();
}
function drawIdentRows(root,rows,ctx,d){const out=$('[data-ident-results]',root);if(!rows.length){out.innerHTML=empty('No students match the selected filter.');return}const rowHtml=rows.map((r,i)=>{const miss=(r.missing_fields||[]).slice(0,3).join(', ')+(r.missing_fields&&r.missing_fields.length>3?' +'+(r.missing_fields.length-3):'');return '<tr><td class="name">'+esc(r.full_name)+'</td><td class="center">'+esc(r.class_code)+'</td><td><b>'+num(r.completion_percent)+'%</b><div class="t83-progress"><i style="width:'+Math.max(0,Math.min(100,num(r.completion_percent)))+'%"></i></div></td><td class="t83-missing">'+esc(miss||'—')+'</td><td class="center"><span class="t83-pill '+statusClass(r.status_label)+'">'+esc(statusText(r.status_label))+'</span></td><td class="center"><button class="t83-btn '+(r.can_edit?'blue':'light')+' small" data-profile="'+esc(r.student_id)+'">'+(r.can_edit?'EDIT PROFILE':'VIEW')+'</button></td></tr>'}).join('');
 const mobile=rows.map(r=>'<div class="t83-mobile-card"><div class="top"><b>'+esc(r.full_name)+'</b><small>'+esc(r.class_code)+'</small></div><div class="meta">SDMS '+esc(r.sdms_code)+' · '+num(r.completion_percent)+'% COMPLETE</div><div class="t83-progress"><i style="width:'+num(r.completion_percent)+'%"></i></div><div class="meta">Missing: '+esc((r.missing_fields||[]).slice(0,3).join(', ')||'None')+'</div><div class="actions"><span class="t83-pill '+statusClass(r.status_label)+'">'+esc(statusText(r.status_label))+'</span><button class="t83-btn '+(r.can_edit?'blue':'light')+' small" data-profile="'+esc(r.student_id)+'">'+(r.can_edit?'EDIT PROFILE':'VIEW PROFILE')+'</button></div></div>').join('');
 out.innerHTML='<div class="t83-table-wrap t83-desktop-only"><table class="t83-table t83-ident-table"><colgroup><col><col style="width:78px"><col style="width:110px"><col style="width:230px"><col style="width:118px"><col style="width:120px"></colgroup><thead><tr><th>STUDENT</th><th>CLASS</th><th>COMPLETE</th><th>MISSING</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>'+rowHtml+'</tbody></table></div><div class="t83-mobile-list">'+mobile+'</div>';
 $$('[data-profile]',out).forEach(b=>b.onclick=()=>openStudentProfile(root.closest('.t83-page')||root,ctx,b.dataset.profile,d));}
function openStudentProfile(mount,ctx,studentId,directory){
 const container=$('[data-t83-ident]',mount)||mount,known=(directory&&directory.rows||[]).find(r=>String(r.student_id)===String(studentId));
 container.innerHTML='<div class="t85-profile-opening"><b>'+esc(known&&known.full_name||'Student Profile')+'</b><span>Opening saved profile…</span></div>';
 rpc('r18683_teacher_student_profile',{p_student_id:studentId}).then(p=>renderProfileEditor(mount,ctx,p,directory)).catch(e=>{container.innerHTML=empty('Profile could not open: '+errorText(e));flash(mount,'Profile could not open: '+errorText(e),'error')});
}
function renderProfileEditor(mount,ctx,p,directory){
 const st=p.student||{},ex=p.identity_extra||{},en=p.current_enrolment||{},health=p.health||{},allow=p.allowed_actions||{},dirRow=(directory&&directory.rows||[]).find(r=>String(r.student_id)===String(st.id))||null,missing=dirRow&&Array.isArray(dirRow.missing_fields)?dirRow.missing_fields:(p.missing_profile_fields||[]),completion=dirRow?num(dirRow.completion_percent):num(st.completion_percent);
 const container=$('[data-t83-ident]',mount)||mount;
 const canEdit=!!allow.edit_identification;
 container.innerHTML='<div class="t83-profile-summary"><div><h3>'+esc(st.full_name)+'</h3><p>'+esc(en.class_code||'')+' · SDMS '+esc(st.sdms_code)+'</p><p><b>Missing:</b> '+esc(missing.join(' · ')||'None')+'</p></div><div class="score"><strong>'+completion+'%</strong><div>PROFILE COMPLETE</div><div class="t83-progress"><i style="width:'+completion+'%"></i></div></div></div>'+
 '<div class="t83-form-tabs">'+[['ident','IDENTIFICATION'],['parents','PARENTS / GUARDIANS'],['address','ADDRESS'],['health','HEALTH & SPECIAL NEEDS']].map((x,i)=>'<button data-formtab="'+x[0]+'" class="'+(i===0?'active':'')+'">'+x[1]+'</button>').join('')+'</div>'+profileForms(st,ex,en,health,canEdit,!!allow.edit_health)+
 '<div class="t83-savebar"><button class="t83-btn light" data-profile-back>← STUDENT LIST</button>'+(canEdit?'<button class="t83-btn blue" data-profile-save>SAVE</button><button class="t83-btn green" data-profile-next>SAVE & NEXT INCOMPLETE →</button>':'')+'</div>';
 $$('[data-formtab]',container).forEach(b=>b.onclick=()=>{$$('[data-formtab]',container).forEach(x=>x.classList.toggle('active',x===b));$$('.t83-form-section',container).forEach(x=>x.classList.toggle('active',x.dataset.section===b.dataset.formtab))});
 $('[data-profile-back]',container).onclick=()=>renderIdentList(mount,ctx,directory,directory&&directory.__lockedClass||null);
 const dob=$('[name="date_of_birth"]',container),age=$('[name="age_auto"]',container);const setAge=()=>{if(!age)return;const v=dob&&dob.value;if(!v){age.value='';return}const d=new Date(v+'T00:00:00'),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;age.value=a>=0?a:''};if(dob){dob.onchange=setAge;setAge()}
 if(canEdit){$('[data-profile-save]',container).onclick=e=>saveProfile(mount,ctx,p,directory,e.currentTarget,false);$('[data-profile-next]',container).onclick=e=>saveProfile(mount,ctx,p,directory,e.currentTarget,true)}
}
function profileForms(st,ex,en,h,canEdit,healthEdit){const dis=canEdit?'':' disabled',hdis=healthEdit?'':' disabled';return '<section class="t83-form-section active" data-section="ident"><div class="t83-form-grid"><div class="t83-field"><label>SDMS Code</label><input value="'+esc(st.sdms_code)+'" readonly></div><div class="t83-field t83-span2"><label>Student Full Name</label><input value="'+esc(st.full_name)+'" readonly></div><div class="t83-field"><label>Sex</label><input value="'+esc(st.sex)+'" readonly></div><div class="t83-field"><label>Date of Birth</label><input type="date" name="date_of_birth" value="'+esc(st.date_of_birth||'')+'"'+dis+'></div><div class="t83-field"><label>Age (Automatic)</label><input name="age_auto" readonly></div><div class="t83-field"><label>Current Class</label><input value="'+esc(en.class_code||'')+'" readonly></div><div class="t83-field"><label>Day / Boarding</label><select name="boarding_type"'+dis+'><option value="">SELECT</option>'+['DAY','BOARDING'].map(x=>'<option '+(norm(ex.boarding_type)===x?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="t83-field t83-span2"><label>Birth Certificate / NID No.</label><input name="birth_cert_nid_no" value="'+esc(ex.birth_cert_nid_no||'')+'"'+dis+'></div><div class="t83-field t83-span2"><label>Other Important Information</label><input name="other_important_information" value="'+esc(ex.other_important_information||'')+'"'+dis+'></div></div></section>'+ 
 '<section class="t83-form-section" data-section="parents"><div class="t83-form-grid"><div class="t83-field t83-span2"><label>Father / Guardian Name *</label><input name="father_guardian_name" value="'+esc(st.father_guardian_name||'')+'"'+dis+'></div><div class="t83-field"><label>Father / Guardian ID *</label><input name="father_guardian_id" value="'+esc(st.father_guardian_id||'')+'"'+dis+'></div><div class="t83-field"><label>Father / Guardian Phone *</label><input name="father_guardian_phone" inputmode="tel" value="'+esc(st.father_guardian_phone||'')+'"'+dis+'></div><div class="t83-field t83-span2"><label>Mother / Guardian Name *</label><input name="mother_guardian_name" value="'+esc(st.mother_guardian_name||'')+'"'+dis+'></div><div class="t83-field"><label>Mother / Guardian ID *</label><input name="mother_guardian_id" value="'+esc(st.mother_guardian_id||'')+'"'+dis+'></div><div class="t83-field"><label>Mother / Guardian Phone *</label><input name="mother_guardian_phone" inputmode="tel" value="'+esc(st.mother_guardian_phone||'')+'"'+dis+'></div><div class="t83-field t83-span2"><label>Other Guardian Name</label><input name="guardian_name" value="'+esc(ex.guardian_name||'')+'"'+dis+'></div><div class="t83-field t83-span2"><label>Other Guardian Phone</label><input name="guardian_phone" inputmode="tel" value="'+esc(ex.guardian_phone||'')+'"'+dis+'></div></div></section>'+ 
 '<section class="t83-form-section" data-section="address"><div class="t83-form-grid"><div class="t83-field"><label>District</label><input name="district" value="'+esc(ex.district||'')+'"'+dis+'></div><div class="t83-field"><label>Sector *</label><input name="sector" value="'+esc(st.sector||'')+'"'+dis+'></div><div class="t83-field"><label>Cell *</label><input name="cell" value="'+esc(st.cell||'')+'"'+dis+'></div><div class="t83-field"><label>Village *</label><input name="village" value="'+esc(st.village||'')+'"'+dis+'></div><div class="t83-field t83-span4"><label>Remarks</label><textarea name="remarks"'+dis+'>'+esc(ex.remarks||'')+'</textarea></div></div></section>'+ 
 '<section class="t83-form-section" data-section="health">'+(h.redacted?'<div class="t83-flash show warn">Health details are available only to the class teacher or authorised welfare role.</div>':'<div class="t83-form-grid"><div class="t83-field"><label>Has Disease?</label><select name="has_disease"'+hdis+'><option value="false" '+(!h.has_disease?'selected':'')+'>NO</option><option value="true" '+(h.has_disease?'selected':'')+'>YES</option></select></div><div class="t83-field"><label>Disease Type</label><input name="disease_type" value="'+esc(h.disease_type||'')+'"'+hdis+'></div><div class="t83-field t83-span2"><label>Disease Details</label><input name="disease_details" value="'+esc(h.disease_details||'')+'"'+hdis+'></div><div class="t83-field"><label>Has Special Need?</label><select name="has_special_need"'+hdis+'><option value="false" '+(!h.has_special_need?'selected':'')+'>NO</option><option value="true" '+(h.has_special_need?'selected':'')+'>YES</option></select></div><div class="t83-field"><label>Special Need Type</label><input name="special_need_type" value="'+esc(h.special_need_type||'')+'"'+hdis+'></div><div class="t83-field"><label>Impairment Type</label><input name="impairment_type" value="'+esc(h.impairment_type||'')+'"'+hdis+'></div><div class="t83-field"><label>Severity</label><input name="severity" value="'+esc(h.severity||'')+'"'+hdis+'></div><div class="t83-field t83-span4"><label>Care / Important Note</label><textarea name="care_notes"'+hdis+'>'+esc(h.care_notes||'')+'</textarea></div></div>')+'</section>'}
function formVal(root,name){const e=$('[name="'+name+'"]',root);return e?String(e.value||'').trim():''}
function recomputeIdentSummary(directory){const rows=directory&&directory.rows||[];directory.summary={total:rows.length,complete:rows.filter(r=>num(r.completion_percent)>=100).length,incomplete:rows.filter(r=>num(r.completion_percent)>=1&&num(r.completion_percent)<100).length,not_started:rows.filter(r=>num(r.completion_percent)===0).length,ready:rows.filter(r=>num(r.completion_percent)>=100&&norm(r.workflow_status)==='SUBMITTED').length,verified:rows.filter(r=>norm(r.workflow_status)==='VERIFIED').length};return directory}
function updateDirectoryRow(directory,row){if(!directory||!row)return directory;const rows=directory.rows||[],i=rows.findIndex(r=>String(r.student_id)===String(row.student_id));if(i>=0)rows[i]=Object.assign({},rows[i],row);else rows.push(row);directory.rows=rows;directory.count=rows.length;return recomputeIdentSummary(directory)}
function saveProfile(mount,ctx,p,directory,btn,next){
 const root=$('[data-t83-ident]',mount)||mount,st=p.student||{},allow=p.allowed_actions||{},c=ctxIds();
 const payload={date_of_birth:formVal(root,'date_of_birth')||null,boarding_type:formVal(root,'boarding_type')||null,birth_cert_nid_no:formVal(root,'birth_cert_nid_no')||null,other_important_information:formVal(root,'other_important_information')||null,father_guardian_name:formVal(root,'father_guardian_name')||null,father_guardian_id:formVal(root,'father_guardian_id')||null,father_guardian_phone:formVal(root,'father_guardian_phone')||null,mother_guardian_name:formVal(root,'mother_guardian_name')||null,mother_guardian_id:formVal(root,'mother_guardian_id')||null,mother_guardian_phone:formVal(root,'mother_guardian_phone')||null,guardian_name:formVal(root,'guardian_name')||null,guardian_phone:formVal(root,'guardian_phone')||null,district:formVal(root,'district')||null,sector:formVal(root,'sector')||null,cell:formVal(root,'cell')||null,village:formVal(root,'village')||null,remarks:formVal(root,'remarks')||null};
 const required=['date_of_birth','father_guardian_name','father_guardian_id','father_guardian_phone','mother_guardian_name','mother_guardian_id','mother_guardian_phone','sector','cell','village'],submit=required.every(k=>!!payload[k]);
 const hp=allow.edit_health?{has_disease:formVal(root,'has_disease')==='true',disease_type:formVal(root,'disease_type')||null,disease_details:formVal(root,'disease_details')||null,has_special_need:formVal(root,'has_special_need')==='true',special_need_type:formVal(root,'special_need_type')||null,impairment_type:formVal(root,'impairment_type')||null,severity:formVal(root,'severity')||null,care_notes:formVal(root,'care_notes')||null}:null;
 const done=busy(btn,next?'SAVING & OPENING NEXT…':'SAVING…');
 rpc('r18685_teacher_save_student_profile',{p_student_id:st.id,p_academic_year_id:c.ayId,p_identity:payload,p_health:hp,p_submit:submit}).then(result=>{
   updateDirectoryRow(directory,result&&result.row);IDENT=directory;IDENT_AT=Date.now();
   flash(mount,submit?'Profile saved and sent for verification.':'Profile saved. Missing required fields remain.','success');
   if(next){const rows=directory&&directory.rows||[],idx=rows.findIndex(r=>String(r.student_id)===String(st.id)),candidate=rows.slice(idx+1).find(r=>r.can_edit&&num(r.completion_percent)<100)||rows.find(r=>r.can_edit&&num(r.completion_percent)<100);if(candidate)return openStudentProfile(mount,ctx,candidate.student_id,directory);renderIdentList(mount,ctx,directory,directory&&directory.__lockedClass||null);flash(mount,'All editable student profiles are complete.','success');return}
   if(result&&result.profile){renderProfileEditor(mount,ctx,result.profile,directory);return}
   renderIdentList(mount,ctx,directory,directory&&directory.__lockedClass||null);
 }).catch(e=>flash(mount,'Save failed: '+errorText(e),'error')).finally(done)
}

/* ========================= ATTENDANCE COMMON ========================= */
function attendanceSummary(rows){let total=rows.length,boys=0,girls=0,present=0,absent=0;rows.forEach(r=>{const sex=norm(r.sex),s=norm(r._status||r.attendance_status||'PRESENT');if(sex==='M'||sex==='MALE')boys++;if(sex==='F'||sex==='FEMALE')girls++;if(s==='PRESENT'||s==='LATE'||s==='SCHOOL_ACTIVITY'||s==='SPORT')present++;else absent++});return{total,boys,girls,present,absent,percent:total?100*present/total:0}}
function attKpis(s){return '<div class="t83-att-summary">'+[['TOTAL',s.total],['BOYS',s.boys],['GIRLS',s.girls],['PRESENT',s.present],['ABSENT',s.absent],['% PRESENT',s.percent.toFixed(1)+'%']].map(x=>'<div class="t83-mini-kpi"><b>'+esc(x[1])+'</b><span>'+x[0]+'</span></div>').join('')+'</div>'}
const ATT_STATUS=['PRESENT','ABSENT','LATE','EXCUSED','SICK','PERMISSION'];
function attRowsHtml(rows){return rows.map((r,i)=>{const s=norm(r.attendance_status||'PRESENT');return '<tr data-att-row="'+esc(r.student_id)+'"><td class="center">'+(i+1)+'</td><td>'+esc(r.sdms_code)+'</td><td class="name">'+esc(r.student_name)+'</td><td class="center">'+esc(r.sex)+'</td><td><select class="t83-status-select" data-att-status>'+ATT_STATUS.map(x=>'<option '+(s===x?'selected':'')+'>'+x+'</option>').join('')+'</select></td><td><input class="t83-reason" data-att-reason value="'+esc(r.reason||'')+'" placeholder="Reason if exception"></td></tr>'}).join('')}
function attMobileHtml(rows){return rows.map(r=>{const s=norm(r.attendance_status||'PRESENT');return '<div class="t83-mobile-card" data-att-row="'+esc(r.student_id)+'"><div class="top"><b>'+esc(r.student_name)+'</b><small>'+esc(r.sex)+' · '+esc(r.sdms_code)+'</small></div><div class="t83-form-grid two"><div class="t83-field"><label>Status</label><select data-att-status>'+ATT_STATUS.map(x=>'<option '+(s===x?'selected':'')+'>'+x+'</option>').join('')+'</select></div><div class="t83-field"><label>Reason</label><input data-att-reason value="'+esc(r.reason||'')+'" placeholder="Reason if needed"></div></div></div>'}).join('')}
function syncAttendanceViews(root,source){const row=source.closest('[data-att-row]'),id=row&&row.dataset.attRow;if(!id)return;const status=$('[data-att-status]',row).value,reason=$('[data-att-reason]',row).value;$$('[data-att-row="'+CSS.escape(id)+'"]',root).forEach(x=>{const s=$('[data-att-status]',x),r=$('[data-att-reason]',x);if(s&&s!==source)s.value=status;if(r&&r!==source)r.value=reason});updateAttSummary(root)}
function collectAttendance(root,base,includeFollow=false){return (base||[]).map(r=>{const row=$('[data-att-row="'+CSS.escape(String(r.student_id))+'"]',root),s=row?$('[data-att-status]',row).value:'PRESENT',reason=row?$('[data-att-reason]',row).value:'';return{student_id:r.student_id,attendance_status:s,arrival_time:null,reason:reason||null,teacher_advice:null,...(includeFollow?{follow_up_required:false}:{})}})}
function validateAttendance(rows){const exceptions=new Set(['ABSENT','LATE','EXCUSED','SICK','PERMISSION']);const bad=rows.find(r=>exceptions.has(r.attendance_status)&&!r.reason);return bad?'Reason is required for every absence, late, excused, sick or permission status.':''}
function wireAttendanceRows(root,base){$$('[data-att-status],[data-att-reason]',root).forEach(e=>e.addEventListener(e.tagName==='SELECT'?'change':'input',()=>syncAttendanceViews(root,e)));const all=$('[data-mark-all-present]',root);if(all)all.onclick=()=>{$$('[data-att-status]',root).forEach(s=>s.value='PRESENT');$$('[data-att-reason]',root).forEach(r=>r.value='');updateAttSummary(root)};root.__t83_att_base=base;updateAttSummary(root)}
function updateAttSummary(root){const base=root.__t83_att_base||[],rows=collectAttendance(root,base);const box=$('[data-att-summary]',root);if(box)box.innerHTML=attKpis(attendanceSummary(rows.map((x,i)=>Object.assign({},base[i],{_status:x.attendance_status}))))}

/* ========================= CLASS ATTENDANCE ========================= */
V.teacherClassAttendance83=function(mount,ctx){
 page(mount,ctx,true);const c=ctxIds();mount.innerHTML=serviceHead('Class Attendance','Default is PRESENT; change only exceptions. Every save gives feedback.')+'<div class="t83-toolbar"><div class="t83-field"><label>Date</label><input type="date" data-ca-date value="'+iso()+'"></div><div class="t83-field t83-span2"><label>Class</label><select data-ca-class><option value="">SELECT CLASS</option></select></div><div class="t83-field"><label>&nbsp;</label><button class="t83-btn blue" data-ca-open>OPEN ATTENDANCE</button></div></div><div data-ca-body></div>';wireBack(mount,ctx);
 getFast().then(d=>{const sel=$('[data-ca-class]',mount),classes=(d.classes||[]).filter(x=>x.is_class_teacher);sel.innerHTML='<option value="">'+(classes.length?'SELECT CLASS':'NO CLASS-TEACHER ASSIGNMENT')+'</option>'+classes.map(x=>'<option value="'+esc(x.class_id)+'">'+esc(x.class_code)+' · '+num(x.student_count)+' students</option>').join('');const requested=window.__T83_CLASS_ATT;delete window.__T83_CLASS_ATT;if(requested&&classes.some(x=>String(x.class_id)===String(requested))){sel.value=requested;openClassAttendance(mount,ctx)}else if(requested){flash(mount,'Class attendance is available only for your assigned class-teacher class.','warn')}}).catch(e=>flash(mount,errorText(e),'error'));
 $('[data-ca-open]',mount).onclick=()=>openClassAttendance(mount,ctx);
};
function openClassAttendance(mount,ctx){const classId=$('[data-ca-class]',mount).value,date=$('[data-ca-date]',mount).value,btn=$('[data-ca-open]',mount);if(!classId)return flash(mount,'Select a class first.','warn');const done=busy(btn,'OPENING…');rpc('r174_teacher_class_attendance_entry',{p_class_id:classId,p_attendance_date:date}).then(d=>renderClassAttendanceEntry(mount,ctx,d)).catch(e=>flash(mount,errorText(e),'error')).finally(done)}
function renderClassAttendanceEntry(mount,ctx,d){const body=$('[data-ca-body]',mount),rows=d.rows||[],c=d.class||{};body.innerHTML=panel(c.class_code+' · '+val(d.attendance_date,''),val(c.class_teacher_names,'Class attendance'),'<div data-att-summary>'+attKpis(attendanceSummary(rows.map(r=>Object.assign({},r,{_status:r.attendance_status||'PRESENT'}))))+'</div><div class="t83-actions" style="justify-content:flex-start;margin-bottom:5px"><button class="t83-btn light small" data-mark-all-present>MARK ALL PRESENT</button><span class="t83-pill '+statusClass(d.workflow_status==='SUBMITTED'?'READY':'INCOMPLETE')+'">'+esc(d.workflow_status||'DRAFT')+'</span></div><div class="t83-table-wrap t83-desktop-only"><table class="t83-table t83-att-table"><colgroup><col style="width:48px"><col style="width:145px"><col><col style="width:74px"><col style="width:145px"><col style="width:260px"></colgroup><thead><tr><th>NO</th><th>SDMS</th><th>STUDENT</th><th>SEX</th><th>STATUS</th><th>REASON</th></tr></thead><tbody>'+attRowsHtml(rows)+'</tbody></table></div><div class="t83-mobile-list">'+attMobileHtml(rows)+'</div><div class="t83-savebar"><button class="t83-btn blue" data-ca-save>SAVE DRAFT</button><button class="t83-btn green" data-ca-submit>SUBMIT ATTENDANCE</button></div>');wireAttendanceRows(body,rows);$('[data-ca-save]',body).onclick=e=>saveClassAttendance(mount,d,e.currentTarget,false);$('[data-ca-submit]',body).onclick=e=>saveClassAttendance(mount,d,e.currentTarget,true)}
function saveClassAttendance(mount,d,btn,submit){const body=$('[data-ca-body]',mount),rows=collectAttendance(body,d.rows||[],true),err=validateAttendance(rows);if(err)return flash(mount,err,'warn');const c=ctxIds(),done=busy(btn,submit?'SUBMITTING…':'SAVING…');rpc('save_class_attendance',{p_academic_year_id:c.ayId,p_term_id:c.termId,p_class_id:d.class.id,p_attendance_date:d.attendance_date,p_rows:rows,p_submit:submit,p_notes:null}).then(x=>{flash(mount,submit?'Attendance submitted successfully.':'Attendance draft saved.','success');renderClassAttendanceEntry(mount,LAST_CTX,x)}).catch(e=>flash(mount,'Attendance save failed: '+errorText(e),'error')).finally(done)}

/* ========================= SUBJECT ATTENDANCE ========================= */
V.teacherSubjectAttendance83=function(mount,ctx){
 page(mount,ctx,true);mount.innerHTML=serviceHead('Subject Attendance','Choose the date; only your published timetable lessons can be recorded.')+'<div class="t83-toolbar"><div class="t83-field"><label>Date</label><input type="date" data-sa-date value="'+iso()+'"></div><div class="t83-field t83-span2"><label>Scheduled Lesson</label><select data-sa-lesson><option value="">SELECT LESSON</option></select></div><div class="t83-field"><label>&nbsp;</label><button class="t83-btn blue" data-sa-open>OPEN ATTENDANCE</button></div></div><div data-sa-body></div>';wireBack(mount,ctx);
 Promise.all([getAllTimetable(),getFast()]).then(()=>fillSubjectLessons(mount));$('[data-sa-date]',mount).onchange=()=>fillSubjectLessons(mount);$('[data-sa-open]',mount).onclick=()=>openSubjectAttendance(mount,ctx);
};
function expandedLessonsForDate(date){const day=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'][new Date(date+'T12:00:00').getDay()],rows=(ALL_TT&&ALL_TT.rows||[]).filter(r=>norm(r.day_of_week)===day),assign=FAST&&FAST.assignments||[],out=[];rows.forEach(r=>{const cc=norm(r.class_code);let cand=assign.filter(a=>String(a.subject_id)===String(r.subject_id)&&String(a.class_code)===String(r.class_code));const m=cc.match(/^([NPS]\d)AB$/);if(m)cand=assign.filter(a=>String(a.subject_id)===String(r.subject_id)&&[m[1]+'A',m[1]+'B'].includes(norm(a.class_code)));if(!cand.length)cand=[{class_id:r.class_id,class_code:r.class_code,subject_id:r.subject_id,subject_name:r.subject_name}];cand.forEach(a=>out.push({class_id:a.class_id,class_code:a.class_code,subject_id:r.subject_id,subject_name:r.subject_name,period_id:r.period_id,start_time:r.start_time,end_time:r.end_time,lesson_number:r.lesson_number}))});return out.sort((a,b)=>String(a.start_time).localeCompare(String(b.start_time))||String(a.class_code).localeCompare(String(b.class_code)))}
function fillSubjectLessons(mount){const date=$('[data-sa-date]',mount).value,sel=$('[data-sa-lesson]',mount),rows=expandedLessonsForDate(date);sel.innerHTML='<option value="">'+(rows.length?'SELECT LESSON':'NO PUBLISHED LESSON ON THIS DATE')+'</option>'+rows.map((x,i)=>'<option value="'+i+'">'+esc(fmtTime(x.start_time)+'–'+fmtTime(x.end_time)+' · '+x.class_code+' · '+x.subject_name)+'</option>').join('');sel.__lessons=rows}
function openSubjectAttendance(mount,ctx){const sel=$('[data-sa-lesson]',mount),date=$('[data-sa-date]',mount).value,btn=$('[data-sa-open]',mount);if(!sel||sel.value==='')return flash(mount,'Select a published lesson first.','warn');const i=Number(sel.value),lesson=sel.__lessons&&sel.__lessons[i];if(!lesson)return flash(mount,'Select a published lesson first.','warn');const done=busy(btn,'OPENING…');rpc('r174_teacher_subject_attendance_entry',{p_class_id:lesson.class_id,p_subject_id:lesson.subject_id,p_lesson_date:date,p_period_id:lesson.period_id}).then(d=>{d.__lesson=lesson;renderSubjectAttendanceEntry(mount,ctx,d)}).catch(e=>flash(mount,errorText(e),'error')).finally(done)}
function renderSubjectAttendanceEntry(mount,ctx,d){const body=$('[data-sa-body]',mount),rows=d.rows||[],c=d.context||{},l=d.__lesson||{};body.innerHTML=panel((c.class_code||l.class_code)+' · '+(c.subject_name||l.subject_name),fmtTime(l.start_time)+'–'+fmtTime(l.end_time)+' · '+val(c.lesson_date,''),'<div data-att-summary>'+attKpis(attendanceSummary(rows.map(r=>Object.assign({},r,{_status:r.attendance_status||'PRESENT'}))))+'</div><div class="t83-actions" style="justify-content:flex-start;margin-bottom:5px"><button class="t83-btn light small" data-mark-all-present>MARK ALL PRESENT</button><span class="t83-pill '+statusClass(d.workflow_status==='SUBMITTED'?'READY':'INCOMPLETE')+'">'+esc(d.workflow_status||'DRAFT')+'</span></div><div class="t83-table-wrap t83-desktop-only"><table class="t83-table t83-att-table"><colgroup><col style="width:48px"><col style="width:145px"><col><col style="width:74px"><col style="width:145px"><col style="width:260px"></colgroup><thead><tr><th>NO</th><th>SDMS</th><th>STUDENT</th><th>SEX</th><th>STATUS</th><th>REASON</th></tr></thead><tbody>'+attRowsHtml(rows)+'</tbody></table></div><div class="t83-mobile-list">'+attMobileHtml(rows)+'</div><div class="t83-savebar"><button class="t83-btn blue" data-sa-save>SAVE DRAFT</button><button class="t83-btn green" data-sa-submit>SUBMIT ATTENDANCE</button></div>');wireAttendanceRows(body,rows);$('[data-sa-save]',body).onclick=e=>saveSubjectAttendance(mount,d,e.currentTarget,false);$('[data-sa-submit]',body).onclick=e=>saveSubjectAttendance(mount,d,e.currentTarget,true)}
function saveSubjectAttendance(mount,d,btn,submit){const body=$('[data-sa-body]',mount),rows=collectAttendance(body,d.rows||[],false),err=validateAttendance(rows);if(err)return flash(mount,err,'warn');const c=ctxIds(),x=d.context||{},l=d.__lesson||{},done=busy(btn,submit?'SUBMITTING…':'SAVING…');rpc('save_subject_attendance',{p_academic_year_id:c.ayId,p_term_id:c.termId,p_class_id:x.class_id||l.class_id,p_subject_id:x.subject_id||l.subject_id,p_lesson_date:x.lesson_date,p_rows:rows,p_period_id:x.period_id||l.period_id,p_submit:submit,p_notes:null}).then(z=>{z.__lesson=l;flash(mount,submit?'Subject attendance submitted successfully.':'Subject attendance draft saved.','success');renderSubjectAttendanceEntry(mount,LAST_CTX,z)}).catch(e=>flash(mount,'Attendance save failed: '+errorText(e),'error')).finally(done)}

/* ========================= MARKS & ASSESSMENTS ========================= */
V.teacherMarks83=function(mount,ctx){
 page(mount,ctx,true);mount.innerHTML=serviceHead('Marks & Assessments','Formula authority: server-side CAMIS / Exam / Final % / Grade / Rank')+'<div class="t83-formula-note">FORMULA SAFETY: This screen does not recalculate CAMIS, exam contribution, final percentage, grade or rank in the browser. It displays the authoritative values returned by Supabase.</div><div class="t83-toolbar"><div class="t83-field t83-search"><label>Class · Subject</label><select data-ma-assign><option value="">SELECT CLASS / SUBJECT</option></select></div><div class="t83-field"><label>&nbsp;</label><button class="t83-btn blue" data-ma-open>OPEN WORKSPACE</button></div></div><div data-ma-body></div>';wireBack(mount,ctx);getFast().then(d=>{const sel=$('[data-ma-assign]',mount),a=d.assignments||[];sel.innerHTML='<option value="">SELECT CLASS / SUBJECT</option>'+a.map((x,i)=>'<option value="'+i+'">'+esc(x.class_code+' · '+x.subject_name)+'</option>').join('');sel.__assign=a}).catch(e=>flash(mount,errorText(e),'error'));$('[data-ma-open]',mount).onclick=()=>openMarksWorkspace(mount,ctx)};
function openMarksWorkspace(mount,ctx){const sel=$('[data-ma-assign]',mount),btn=$('[data-ma-open]',mount);if(!sel||sel.value==='')return flash(mount,'Select a class and subject first.','warn');const i=Number(sel.value),a=sel.__assign&&sel.__assign[i];if(!a)return flash(mount,'Select a class and subject first.','warn');const done=busy(btn,'OPENING…');rpc('r174_teacher_marks_workspace',{p_class_id:a.class_id,p_subject_id:a.subject_id}).then(d=>{d.__assignment=a;renderMarksWorkspace(mount,ctx,d)}).catch(e=>flash(mount,errorText(e),'error')).finally(done)}
function renderMarksWorkspace(mount,ctx,d){const body=$('[data-ma-body]',mount),ass=d.assessments||[],cats=d.categories||[],a=d.__assignment||{};body.innerHTML=panel(a.class_code+' · '+a.subject_name,num(d.student_count)+' students · CAMIS max '+val(d.camis_max,''),'<div class="t83-toolbar" style="grid-template-columns:minmax(130px,1fr) 90px auto"><div class="t83-field"><label>Assessment Type</label><select data-new-cat><option value="">SELECT TYPE</option>'+cats.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('')+'</select></div><div class="t83-field"><label>Max Mark</label><input type="number" min="1" data-new-max></div><div class="t83-field"><label>&nbsp;</label><button class="t83-btn green" data-new-assessment>CREATE / OPEN</button></div></div><div class="t83-table-wrap"><table class="t83-table"><thead><tr><th>ASSESSMENT</th><th style="width:12%">MAX</th><th style="width:14%">DATE</th><th style="width:14%">STATUS</th><th style="width:14%">PROGRESS</th><th style="width:12%">ACTION</th></tr></thead><tbody>'+(ass.length?ass.map(x=>'<tr><td class="name">'+esc(x.assessment_name)+'</td><td class="center">'+esc(x.max_mark)+'</td><td class="center">'+esc(x.assessment_date||'—')+'</td><td class="center">'+esc(x.workflow_status||x.status||'DRAFT')+'</td><td class="center">'+num(x.completed_or_status_rows)+' / '+num(d.student_count)+'</td><td class="center"><button class="t83-btn blue small" data-open-ass="'+esc(x.assessment_id)+'">OPEN</button></td></tr>').join(''):'<tr><td colspan="6">'+empty('No assessment yet. Create one above.')+'</td></tr>')+'</tbody></table></div>')+'<div data-ma-entry></div>';const nb=$('[data-new-assessment]',body);nb.onclick=()=>{const cat=$('[data-new-cat]',body).value,max=Number($('[data-new-max]',body).value);if(!cat||!max||max<=0)return flash(mount,'Select assessment type and enter a valid maximum mark.','warn');const done=busy(nb,'CREATING…');rpc('r174_teacher_open_assessment',{p_class_id:a.class_id,p_subject_id:a.subject_id,p_category_id:cat,p_max_mark:max}).then(x=>{x.__assignment=a;renderMarksEntry(mount,x)}).catch(e=>flash(mount,errorText(e),'error')).finally(done)};$$('[data-open-ass]',body).forEach(b=>b.onclick=()=>{const done=busy(b,'OPENING…');rpc('r174_teacher_marks_entry_data',{p_class_id:a.class_id,p_subject_id:a.subject_id,p_assessment_id:b.dataset.openAss}).then(x=>{x.__assignment=a;renderMarksEntry(mount,x)}).catch(e=>flash(mount,errorText(e),'error')).finally(done)})}
function fnum(v){return v==null||v===''?'—':Number(v).toFixed(Number(v)%1?1:0)}
function formulaPair(v,m){return v==null?'—':fnum(v)+(m!=null?' / '+fnum(m):'')}
function renderMarksEntry(mount,d){const entry=$('[data-ma-entry]',mount),rows=d.rows||[],as=d.assessment||{},a=d.__assignment||{},editable=as.editable!==false;entry.innerHTML=panel('MARK ENTRY · '+val(as.assessment_name,''),'Maximum '+val(as.max_mark,'')+' · '+val(as.workflow_status,'DRAFT'),'<div class="t83-formula-note">Calculated columns are READ ONLY and come from the server formula engine.</div><div class="t83-table-wrap t83-desktop-only"><table class="t83-table t83-marks-table"><colgroup><col style="width:4%"><col style="width:9%"><col style="width:19%"><col style="width:13%"><col style="width:9%"><col style="width:9%"><col style="width:9%"><col style="width:9%"><col style="width:8%"><col style="width:6%"><col style="width:5%"></colgroup><thead><tr><th>NO</th><th>SDMS</th><th>STUDENT</th><th>CURRENT ASSESSMENT</th><th>ASS. TOTAL</th><th>CAMIS E.U</th><th>CAMIS EXAM</th><th>TOTAL CAMIS</th><th>FINAL %</th><th>GRADE</th><th>RANK</th></tr></thead><tbody>'+rows.map((r,i)=>marksRow(r,i,editable)).join('')+'</tbody></table></div><div class="t83-mobile-list">'+rows.map((r,i)=>marksMobile(r,i,editable)).join('')+'</div>'+(editable?'<div class="t83-savebar"><button class="t83-btn blue" data-marks-save>SAVE DRAFT</button><button class="t83-btn green" data-marks-submit>SUBMIT MARKS</button></div>':'<div class="t83-flash show info">This assessment is not editable in its current workflow status.</div>'));wireMarkInputs(entry,rows);if(editable){$('[data-marks-save]',entry).onclick=e=>saveMarks(mount,d,e.currentTarget,false);$('[data-marks-submit]',entry).onclick=e=>saveMarks(mount,d,e.currentTarget,true)}}
function marksRow(r,i,editable){const status=norm(r.entry_status||(r.entry_mark!=null?'MARK':'N'));return '<tr data-mark-row="'+esc(r.student_id)+'"><td class="center">'+(i+1)+'</td><td>'+esc(r.sdms_code)+'</td><td class="name">'+esc(r.student_name)+'</td><td><div class="t83-mark-entry"><input type="number" step="0.01" min="0" max="'+esc(r.current_max||'')+'" data-mark-value value="'+esc(r.entry_mark==null?'':r.entry_mark)+'" '+(!editable||status!=='MARK'?'disabled':'')+'><select data-mark-status '+(!editable?'disabled':'')+'>'+['MARK','A','E','S','N','P'].map(x=>'<option '+(status===x?'selected':'')+'>'+x+'</option>').join('')+'</select></div></td><td class="center t83-formula">'+esc(formulaPair(r.all_ass_obtained,r.all_ass_max))+'</td><td class="center t83-formula">'+esc(formulaPair(r.camis_eu,r.camis_max))+'</td><td class="center t83-formula">'+esc(formulaPair(r.camis_exam,r.camis_exam_max))+'</td><td class="center t83-formula">'+esc(formulaPair(r.total_marks,r.total_marks_max))+'</td><td class="center t83-formula">'+esc(pct(r.percentage))+'</td><td class="center t83-formula">'+esc(val(r.grade,''))+'</td><td class="center t83-formula">'+esc(val(r.rank,''))+'</td></tr>'}
function marksMobile(r,i,editable){const status=norm(r.entry_status||(r.entry_mark!=null?'MARK':'N'));return '<div class="t83-mobile-card" data-mark-row="'+esc(r.student_id)+'"><div class="top"><b>'+(i+1)+'. '+esc(r.student_name)+'</b><small>'+esc(r.sdms_code)+'</small></div><div class="t83-form-grid two"><div class="t83-field"><label>Mark</label><input type="number" step="0.01" min="0" max="'+esc(r.current_max||'')+'" data-mark-value value="'+esc(r.entry_mark==null?'':r.entry_mark)+'" '+(!editable||status!=='MARK'?'disabled':'')+'></div><div class="t83-field"><label>Status</label><select data-mark-status '+(!editable?'disabled':'')+'>'+['MARK','A','E','S','N','P'].map(x=>'<option '+(status===x?'selected':'')+'>'+x+'</option>').join('')+'</select></div></div><div class="meta"><b>ASS:</b> '+esc(formulaPair(r.all_ass_obtained,r.all_ass_max))+' · <b>CAMIS:</b> '+esc(formulaPair(r.camis_eu,r.camis_max))+' · <b>EXAM:</b> '+esc(formulaPair(r.camis_exam,r.camis_exam_max))+' · <b>FINAL:</b> '+esc(pct(r.percentage))+' · <b>'+esc(val(r.grade,''))+'</b> · Rank '+esc(val(r.rank,''))+'</div></div>'}
function wireMarkInputs(root,rows){const initial=new Map(rows.map(r=>[String(r.student_id),{mark:r.entry_mark==null?'':String(r.entry_mark),status:norm(r.entry_status||(r.entry_mark!=null?'MARK':'N'))}]));root.__markInitial=initial;$$('[data-mark-status]',root).forEach(s=>s.onchange=()=>{const row=s.closest('[data-mark-row]'),id=row.dataset.markRow,status=s.value;$$('[data-mark-row="'+CSS.escape(id)+'"]',root).forEach(x=>{const ss=$('[data-mark-status]',x),inp=$('[data-mark-value]',x);if(ss!==s)ss.value=status;if(status!=='MARK'){inp.value='';inp.disabled=true}else inp.disabled=false})});$$('[data-mark-value]',root).forEach(inp=>inp.oninput=()=>{const row=inp.closest('[data-mark-row]'),id=row.dataset.markRow;$$('[data-mark-row="'+CSS.escape(id)+'"]',root).forEach(x=>{const ii=$('[data-mark-value]',x),ss=$('[data-mark-status]',x);if(ii!==inp)ii.value=inp.value;if(inp.value!==''){ss.value='MARK';ii.disabled=false}})})}
function collectMarks(root,submit){const map=new Map();$$('[data-mark-row]',root).forEach(row=>{const id=row.dataset.markRow;if(map.has(id))return;const status=$('[data-mark-status]',row).value,inp=$('[data-mark-value]',row),mark=inp&&inp.value!==''?Number(inp.value):null;map.set(id,{student_id:id,mark:status==='MARK'?mark:null,mark_status:status,remarks:null})});const all=Array.from(map.values()),init=root.__markInitial||new Map();if(submit){const bad=all.find(x=>(x.mark_status==='MARK'&&x.mark==null)||['N','P'].includes(x.mark_status));if(bad)throw new Error('Complete every student with a numeric mark or A / E / S before Submit.')}return all.filter(x=>{const z=init.get(String(x.student_id))||{mark:'',status:'N'};return String(x.mark==null?'':x.mark)!==String(z.mark)||x.mark_status!==z.status})}
function saveMarks(mount,d,btn,submit){const entry=$('[data-ma-entry]',mount);let rows;try{rows=collectMarks(entry,submit)}catch(e){return flash(mount,errorText(e),'warn')}const as=d.assessment||{},done=busy(btn,submit?'SUBMITTING…':'SAVING…');rpc('r174_teacher_save_marks',{p_assessment_id:as.id,p_rows:rows,p_submit:submit}).then(x=>{x.__assignment=d.__assignment;flash(mount,submit?'Marks submitted successfully.':'Marks draft saved successfully.','success');renderMarksEntry(mount,x)}).catch(e=>flash(mount,'Marks save failed: '+errorText(e),'error')).finally(done)}

/* ========================= STUDENT PERFORMANCE ========================= */
V.teacherPerformance83=function(mount,ctx){
 page(mount,ctx,true);mount.innerHTML=serviceHead('Student Performance','Select one class/subject. Final results use server-calculated percentages.')+'<div class="t83-toolbar"><div class="t83-field t83-search"><label>Class · Subject</label><select data-perf-assign><option value="">SELECT CLASS / SUBJECT</option></select></div><div class="t83-field"><label>&nbsp;</label><button class="t83-btn blue" data-perf-load>SHOW PERFORMANCE</button></div></div><div data-perf-body></div>';wireBack(mount,ctx);getFast().then(d=>{const sel=$('[data-perf-assign]',mount),a=d.assignments||[];sel.innerHTML='<option value="">SELECT CLASS / SUBJECT</option>'+a.map((x,i)=>'<option value="'+i+'">'+esc(x.class_code+' · '+x.subject_name)+'</option>').join('');sel.__assign=a}).catch(e=>flash(mount,errorText(e),'error'));$('[data-perf-load]',mount).onclick=()=>{const sel=$('[data-perf-assign]',mount),btn=$('[data-perf-load]',mount);if(!sel||sel.value==='')return flash(mount,'Select a class and subject first.','warn');const a=sel.__assign&&sel.__assign[Number(sel.value)];if(!a)return flash(mount,'Select a class and subject first.','warn');const done=busy(btn,'ANALYSING…');rpc('r174_teacher_marks_entry_data',{p_class_id:a.class_id,p_subject_id:a.subject_id,p_assessment_id:null}).then(d=>renderPerformance(mount,a,d)).catch(e=>flash(mount,errorText(e),'error')).finally(done)}};
function renderPerformance(mount,a,d){const rows=(d.rows||[]).filter(r=>r.percentage!=null),avg=rows.length?rows.reduce((s,r)=>s+num(r.percentage),0)/rows.length:0,passed=rows.filter(r=>num(r.percentage)>=50).length,failed=rows.filter(r=>num(r.percentage)<50).length,sorted=rows.slice().sort((x,y)=>num(y.percentage)-num(x.percentage));$('[data-perf-body]',mount).innerHTML='<div class="t83-kpis">'+kpi(rows.length,'RESULTS','blue')+kpi(avg.toFixed(1)+'%','AVERAGE','navy')+kpi(passed,'PASSED ≥50%','green')+kpi(failed,'FAILED <50%','red')+'</div>'+panel(a.class_code+' · '+a.subject_name,'Highest '+(sorted[0]?sorted[0].student_name+' '+pct(sorted[0].percentage):'—')+' · Lowest '+(sorted.length?sorted[sorted.length-1].student_name+' '+pct(sorted[sorted.length-1].percentage):'—'),'<div class="t83-table-wrap t83-desktop-only"><table class="t83-table"><thead><tr><th style="width:7%">RANK</th><th>STUDENT</th><th style="width:16%">TOTAL CAMIS</th><th style="width:12%">FINAL %</th><th style="width:10%">GRADE</th><th style="width:13%">STATUS</th></tr></thead><tbody>'+sorted.map(r=>'<tr><td class="center">'+esc(val(r.rank,''))+'</td><td class="name">'+esc(r.student_name)+'</td><td class="center">'+esc(formulaPair(r.total_marks,r.total_marks_max))+'</td><td class="center"><b>'+esc(pct(r.percentage))+'</b></td><td class="center">'+esc(val(r.grade,''))+'</td><td class="center"><span class="t83-pill '+(num(r.percentage)>=50?'complete':'notstarted')+'">'+(num(r.percentage)>=50?'PASS':'FAIL')+'</span></td></tr>').join('')+'</tbody></table></div><div class="t83-mobile-list">'+sorted.map(r=>'<div class="t83-mobile-card"><div class="top"><b>#'+esc(val(r.rank,''))+' '+esc(r.student_name)+'</b><span class="t83-pill '+(num(r.percentage)>=50?'complete':'notstarted')+'">'+(num(r.percentage)>=50?'PASS':'FAIL')+'</span></div><div class="meta">Final '+esc(pct(r.percentage))+' · Grade '+esc(val(r.grade,''))+' · Total '+esc(formulaPair(r.total_marks,r.total_marks_max))+'</div></div>').join('')+'</div>')}

/* ========================= REPORTS ========================= */
V.teacherReports83=function(mount,ctx){
 page(mount,ctx,true);const c=ctxIds();mount.innerHTML=serviceHead('Teacher Reports','Only teacher-owned reports in the live report catalog','<button class="t83-btn blue small" data-t83-print>PRINT</button>')+'<div data-report-body><div class="t85-inline-state">Report area is ready; confirming your current report catalogue…</div></div>';wireBack(mount,ctx);$('[data-t83-print]',mount).onclick=()=>window.print();rpc('r166_teacher_reports',{p_academic_year_id:c.ayId,p_term_id:c.termId}).then(d=>{const cat=d.catalog||[],sub=d.submissions||[];$('[data-report-body]',mount).innerHTML='<div class="t83-kpis">'+kpi(cat.length,'REPORT TYPES','blue')+kpi(sub.length,'SUBMISSIONS','green')+kpi(sub.filter(x=>norm(x.submission_status)==='PENDING').length,'PENDING','gold')+kpi(sub.filter(x=>norm(x.submission_status)==='SUBMITTED').length,'SUBMITTED','navy')+'</div>'+panel('AVAILABLE REPORTS','Print/download remains enabled by the backend','<div class="t83-table-wrap"><table class="t83-table"><thead><tr><th>REPORT</th><th style="width:18%">GROUP</th><th style="width:18%">PERIODS</th><th style="width:12%">PAPER</th></tr></thead><tbody>'+cat.map(r=>'<tr><td class="name">'+esc(r.report_name)+'<br><small>'+esc(r.description||'')+'</small></td><td>'+esc(r.service_group||'')+'</td><td>'+esc([r.supports_daily&&'DAILY',r.supports_weekly&&'WEEKLY',r.supports_monthly&&'MONTHLY',r.supports_termly&&'TERMLY'].filter(Boolean).join(' · '))+'</td><td class="center">'+esc((r.paper_size||'A4')+' '+(r.orientation||''))+'</td></tr>').join('')+'</tbody></table></div>')+(sub.length?panel('REPORT SUBMISSIONS','Current term','<div class="t83-table-wrap"><table class="t83-table"><thead><tr><th>REPORT</th><th>PERIOD</th><th>DUE</th><th>STATUS</th></tr></thead><tbody>'+sub.map(x=>'<tr><td>'+esc(x.report_name)+'</td><td>'+esc(x.reporting_period||'')+'</td><td>'+esc(x.due_date||'—')+'</td><td>'+esc(x.submission_status||'—')+'</td></tr>').join('')+'</tbody></table></div>'):'')}).catch(e=>{const body=$('[data-report-body]',mount);if(body)body.innerHTML=empty('Reports unavailable: '+errorText(e));flash(mount,'Reports could not open: '+errorText(e),'error')})};


/* ========================= MY CLUB ========================= */
V.teacherClub85=function(mount,ctx){
 page(mount,ctx,true);const c=ctxIds();mount.innerHTML=serviceHead('My Club','Only clubs where you are the assigned patron','<button class="t83-btn green small" data-t83-refresh>REFRESH</button>')+'<div class="t83-toolbar t83-roster-tools"><div class="t83-field t83-search"><label>Search member / SDMS</label><input data-club-search placeholder="Search within my club members…"></div><div class="t83-field"><label>Club</label><div class="t85-count" data-club-count>—</div></div></div><div data-club-body><div class="t85-inline-state">Club area is ready; confirming your current patron assignment…</div></div>';wireBack(mount,ctx);
 let data=null;
 const draw=()=>{const body=$('[data-club-body]',mount),q=norm($('[data-club-search]',mount).value),clubs=data&&data.rows||[];if(!body)return;$('[data-club-count]',mount).textContent=clubs.length+' CLUB'+(clubs.length===1?'':'S');if(!clubs.length){body.innerHTML=empty('No active club is assigned to this teacher.');return}body.innerHTML=clubs.map(cl=>{const members=(cl.members||[]).filter(x=>!q||norm((x.student_name||'')+' '+(x.sdms_code||'')+' '+(x.class_code||'')).includes(q));const desk='<div class="t83-table-wrap t83-desktop-only"><table class="t83-table t85-club-table"><colgroup><col style="width:48px"><col style="width:145px"><col><col style="width:76px"><col style="width:88px"></colgroup><thead><tr><th>NO</th><th>SDMS</th><th>STUDENT NAME</th><th>SEX</th><th>CLASS</th></tr></thead><tbody>'+members.map((x,i)=>'<tr><td class="center">'+(i+1)+'</td><td>'+esc(x.sdms_code)+'</td><td class="name">'+esc(x.student_name)+'</td><td class="center">'+esc(x.sex)+'</td><td class="center">'+esc(x.class_code||'—')+'</td></tr>').join('')+'</tbody></table></div>';const mobile='<div class="t83-mobile-list">'+members.map((x,i)=>'<div class="t83-mobile-card"><div class="top"><b>'+(i+1)+'. '+esc(x.student_name)+'</b><small>'+esc(x.class_code||'—')+'</small></div><div class="meta">SDMS '+esc(x.sdms_code)+' · '+esc(x.sex||'—')+'</div></div>').join('')+'</div>';return panel(cl.club_name||cl.club_code||'MY CLUB',(cl.activity_day||'—')+' · '+(cl.activity_time||'—')+' · '+num(cl.member_count)+' members',members.length?desk+mobile:empty('No club member matches this search.'))}).join('')};
 const load=force=>{if(force)data=null;return rpc('r166_teacher_club_workspace',{p_academic_year_id:c.ayId,p_search:null}).then(d=>{data=d;draw();return d}).catch(e=>{const body=$('[data-club-body]',mount);if(body)body.innerHTML=empty('Club workspace unavailable: '+errorText(e));flash(mount,'Club workspace could not open: '+errorText(e),'error');throw e})};
 $('[data-club-search]',mount).addEventListener('input',draw);const rb=$('[data-t83-refresh]',mount);rb.onclick=()=>{const done=busy(rb,'REFRESHING…');load(true).then(()=>flash(mount,'Club workspace refreshed.','success')).catch(()=>{}).finally(done)};load(false).catch(()=>{});
};

/* ========================= LESSON PLANS ========================= */
V.teacherLessonPlans85=function(mount,ctx){
 page(mount,ctx,true);mount.innerHTML=serviceHead('Lesson Plans','Create, save draft and submit plans for your assigned class / subject','<button class="t83-btn green small" data-t83-refresh>REFRESH</button>')+'<div data-lp-body><div class="t85-inline-state">Lesson-plan area is ready; confirming your current plans…</div></div>';wireBack(mount,ctx);
 let workspace={lesson_plans:[]},assignments=[];
 const draw=()=>{const root=$('[data-lp-body]',mount),rows=workspace.lesson_plans||[],draft=rows.filter(x=>norm(x.status)==='DRAFT').length,submitted=rows.filter(x=>norm(x.status)==='SUBMITTED').length,returned=rows.filter(x=>norm(x.status)==='RETURNED').length;root.innerHTML='<div class="t83-kpis">'+kpi(rows.length,'TOTAL PLANS','blue')+kpi(draft,'DRAFT','gold')+kpi(submitted,'SUBMITTED','green')+kpi(returned,'RETURNED','red')+'</div>'+panel('NEW LESSON PLAN','Only your active assignments are available','<div class="t83-form-grid"><div class="t83-field t83-span2"><label>Class / Subject *</label><select data-lp-assign>'+(assignments.length?assignments.map((a,i)=>'<option value="'+i+'">'+esc(a.class_code+' · '+a.subject_name)+'</option>').join(''):'<option value="">NO ACTIVE ASSIGNMENT</option>')+'</select></div><div class="t83-field"><label>Lesson Date *</label><input type="date" data-lp-date value="'+iso()+'"></div><div class="t83-field"><label>Lesson Title *</label><input data-lp-title placeholder="Lesson title"></div><div class="t83-field t83-span2"><label>Lesson Objective</label><textarea data-lp-objective></textarea></div><div class="t83-field t83-span2"><label>Content Summary</label><textarea data-lp-content></textarea></div><div class="t83-field t83-span2"><label>Learning Activities</label><textarea data-lp-activities></textarea></div><div class="t83-field"><label>Assessment Method</label><input data-lp-assess></div><div class="t83-field"><label>Remedial Plan</label><input data-lp-remedial></div><div class="t83-field t83-span2"><label>Evidence / Reference</label><input data-lp-evidence placeholder="Optional URL or reference"></div></div><div class="t83-savebar"><button class="t83-btn blue" data-lp-draft '+(!assignments.length?'disabled':'')+'>SAVE DRAFT</button><button class="t83-btn green" data-lp-submit '+(!assignments.length?'disabled':'')+'>SUBMIT PLAN</button></div>')+panel('MY LESSON PLANS',rows.length+' plan(s)',lessonPlansHtml(rows));
 const save=(submit,btn)=>{if(!assignments.length)return flash(mount,'No active class / subject assignment is available.','warn');const ai=Number($('[data-lp-assign]',root).value||0),a=assignments[ai],date=$('[data-lp-date]',root).value,title=$('[data-lp-title]',root).value.trim();if(!a||!date||!title)return flash(mount,'Class / subject, lesson date and lesson title are required.','warn');const done=busy(btn,submit?'SUBMITTING…':'SAVING…');rpc('save_teacher_lesson_plan',{p_class_id:a.class_id,p_subject_id:a.subject_id,p_lesson_date:date,p_lesson_title:title,p_lesson_objective:$('[data-lp-objective]',root).value.trim()||null,p_content_summary:$('[data-lp-content]',root).value.trim()||null,p_learning_activities:$('[data-lp-activities]',root).value.trim()||null,p_assessment_method:$('[data-lp-assess]',root).value.trim()||null,p_remedial_plan:$('[data-lp-remedial]',root).value.trim()||null,p_evidence_url:$('[data-lp-evidence]',root).value.trim()||null,p_submit:submit}).then(()=>rpc('get_imihigo_workspace',{p_role_code:'TEACHER',p_staff_id:null})).then(w=>{workspace=w||{lesson_plans:[]};draw();flash(mount,submit?'Lesson plan submitted successfully.':'Lesson plan draft saved successfully.','success')}).catch(e=>flash(mount,'Lesson plan save failed: '+errorText(e),'error')).finally(done)};
 const db=$('[data-lp-draft]',root),sb=$('[data-lp-submit]',root);if(db)db.onclick=()=>save(false,db);if(sb)sb.onclick=()=>save(true,sb)
 };
 const load=()=>Promise.all([getFast(),rpc('get_imihigo_workspace',{p_role_code:'TEACHER',p_staff_id:null})]).then(([f,w])=>{assignments=f&&f.assignments||[];workspace=w||{lesson_plans:[]};draw()}).catch(e=>{const root=$('[data-lp-body]',mount);if(root)root.innerHTML=empty('Lesson plans unavailable: '+errorText(e));flash(mount,'Lesson plans could not open: '+errorText(e),'error');throw e});
 const rb=$('[data-t83-refresh]',mount);rb.onclick=()=>{const done=busy(rb,'REFRESHING…');load().then(()=>flash(mount,'Lesson plans refreshed.','success')).catch(()=>{}).finally(done)};load().catch(()=>{});
};
function lessonPlansHtml(rows){if(!rows.length)return empty('No lesson plan has been recorded for this term.');const sorted=rows.slice().sort((a,b)=>String(b.lesson_date||'').localeCompare(String(a.lesson_date||'')));const desk='<div class="t83-table-wrap t83-desktop-only"><table class="t83-table t85-lp-table"><colgroup><col style="width:105px"><col style="width:85px"><col style="width:160px"><col><col style="width:105px"><col style="width:220px"></colgroup><thead><tr><th>DATE</th><th>CLASS</th><th>SUBJECT</th><th>LESSON</th><th>STATUS</th><th>REVIEW COMMENT</th></tr></thead><tbody>'+sorted.map(x=>'<tr><td class="center">'+esc(x.lesson_date||'—')+'</td><td class="center">'+esc(x.class_code||'—')+'</td><td>'+esc(x.subject_name||x.subject_code||'—')+'</td><td class="name">'+esc(x.lesson_title||'LESSON PLAN')+'</td><td class="center"><span class="t83-pill '+(norm(x.status)==='SUBMITTED'?'complete':norm(x.status)==='RETURNED'?'notstarted':'incomplete')+'">'+esc(norm(x.status||'DRAFT'))+'</span></td><td>'+esc(x.review_comment||'—')+'</td></tr>').join('')+'</tbody></table></div>';const mobile='<div class="t83-mobile-list">'+sorted.map(x=>'<div class="t83-mobile-card"><div class="top"><b>'+esc(x.lesson_title||'LESSON PLAN')+'</b><span class="t83-pill '+(norm(x.status)==='SUBMITTED'?'complete':norm(x.status)==='RETURNED'?'notstarted':'incomplete')+'">'+esc(norm(x.status||'DRAFT'))+'</span></div><div class="meta">'+esc(x.lesson_date||'—')+' · '+esc(x.class_code||'—')+' · '+esc(x.subject_name||x.subject_code||'—')+'</div>'+(x.review_comment?'<div class="meta">Review: '+esc(x.review_comment)+'</div>':'')+'</div>').join('')+'</div>';return desk+mobile}

/* ========================= ACCOUNT ========================= */
V.teacherAccount83=function(mount,ctx){
 page(mount,ctx,true);LAST_CTX=ctx;const p=window.BOOT&&BOOT.profile||{},c=ctxIds();
 mount.innerHTML=serviceHead('Account','Teacher profile and password security')+
 '<div class="t83-grid2">'+
 panel('MY PROFILE','Authenticated staff account','<div class="t83-list"><div class="t83-list-row"><div><b>FULL NAME</b><span>'+esc(p.full_name||'')+'</span></div></div><div class="t83-list-row"><div><b>STAFF CODE</b><span>'+esc(p.staff_code||'')+'</span></div></div><div class="t83-list-row"><div><b>EMAIL</b><span>'+esc(p.email||'')+'</span></div></div><div class="t83-list-row"><div><b>PHONE</b><span>'+esc(p.phone||'')+'</span></div></div><div class="t83-list-row"><div><b>ROLE / CONTEXT</b><span>TEACHER · '+esc(c.ay)+' · '+esc(c.term)+'</span></div></div></div>')+
 panel('CHANGE PASSWORD','Updates your real Supabase login password','<div class="t83-form-grid two"><div class="t83-field"><label>New Password</label><input type="password" data-ac-new autocomplete="new-password" placeholder="At least 8 characters"></div><div class="t83-field"><label>Confirm New Password</label><input type="password" data-ac-confirm autocomplete="new-password" placeholder="Repeat new password"></div></div><div class="t83-actions" style="justify-content:flex-start;margin-top:6px"><button class="t83-btn blue" data-ac-save>UPDATE PASSWORD</button></div>')+
 '</div>';wireBack(mount,ctx);
 const b=$('[data-ac-save]',mount);b.onclick=async()=>{const a=$('[data-ac-new]',mount).value,z=$('[data-ac-confirm]',mount).value;if(a.length<8)return flash(mount,'Use at least 8 characters for the new password.','warn');if(a!==z)return flash(mount,'The two passwords do not match.','warn');const ss=L&&typeof L.session==='function'?L.session():null;if(!ss||!ss.access_token)return flash(mount,'Your login session is missing. Sign in again.','error');const done=busy(b,'UPDATING…');try{const res=await fetch('https://xydrwpbgikwsxerqwkik.supabase.co/auth/v1/user',{method:'PUT',cache:'no-store',headers:{apikey:'sb_publishable_-k49Hut2E8SNIJLvofL4JQ_jW1K865r',Authorization:'Bearer '+ss.access_token,'Content-Type':'application/json'},body:JSON.stringify({password:a})});const tx=await res.text();let data={};try{data=tx?JSON.parse(tx):{}}catch(_){}if(!res.ok)throw new Error(data.message||data.error_description||data.error||('HTTP '+res.status));$('[data-ac-new]',mount).value='';$('[data-ac-confirm]',mount).value='';flash(mount,'Password updated successfully. Your username / staff code did not change.','success')}catch(e){flash(mount,'Password update failed: '+errorText(e),'error')}finally{done()}}
};

/* R186.85 fail-visible guard: no unhandled teacher operation is allowed to fail silently. */
let T85_LAST_GLOBAL_ERROR=0;
function teacherErrorNotice(message){const now=Date.now();if(now-T85_LAST_GLOBAL_ERROR<1800)return;T85_LAST_GLOBAL_ERROR=now;notify(message,'error')}
window.addEventListener('unhandledrejection',event=>{if(!document.body.hasAttribute('data-t83-view'))return;const reason=event&&event.reason;teacherErrorNotice('Operation failed: '+errorText(reason))});
window.addEventListener('error',event=>{if(!document.body.hasAttribute('data-t83-view'))return;if(event&&event.target&&event.target!==window){teacherErrorNotice('A required page resource could not load. Refresh once and retry.');return}if(event&&event.error)teacherErrorNotice('Screen error: '+errorText(event.error))},true);

/* Re-render sidebar immediately if loader finishes after initial authenticated shell paint. */
try{document.dispatchEvent(new CustomEvent('gsm:teacher-portal-ready',{detail:{revision:'R186.85'}}))}catch(_){}
})();
